In [2]:
from sklearn.datasets import make_classification
import torch


In [3]:
X, y = make_classification(
	n_samples = 10,
	n_features = 2,
	n_informative = 2,
	n_redundant = 0,
	n_classes = 2,
	random_state = 42
)
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [5]:
## convert data into pytorch tensor

In [6]:
X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.long)
X, y

(tensor([[ 1.0683, -0.9701],
         [-1.1402, -0.8388],
         [-2.8954,  1.9769],
         [-0.7206, -0.9606],
         [-1.9629, -0.9923],
         [-0.9382, -0.5430],
         [ 1.7273, -1.1858],
         [ 1.7774,  1.5116],
         [ 1.8997,  0.8344],
         [-0.5872, -1.9717]]),
 tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [7]:
from torch.utils.data import Dataset, DataLoader

In [8]:
class CoustemDataset(Dataset):

	def __init__(self, features, label):
		self.features = features
		self.label = label

	def __len__(self):

		return self.features.shape[0]

	def __getitem__(self, index):

		return self.features[index], self.label[index]

In [9]:
dataset = CoustemDataset(X,y)
dataset

In [10]:
dataset.features

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [12]:
dataset.label

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [13]:
len(dataset)

10

In [15]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [17]:
x1, y1 = dataset[2]
x1, y1

(tensor([-2.8954,  1.9769]), tensor(0))

In [18]:
x1

tensor([-2.8954,  1.9769])

In [19]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [23]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
dataloader

In [30]:
dataloader.drop_last

False

In [33]:
for batch_feature, batch_label in dataloader:

	print(batch_feature)
	print(batch_label)
	print("-"*50)


tensor([[ 1.0683, -0.9701],
        [-1.9629, -0.9923]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.7273, -1.1858]])
tensor([1, 1])
--------------------------------------------------


## Creating One Demo on Cancer Dataset 

In [115]:
## apply this function to the application

In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [117]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [118]:
df.head(5)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [119]:
df.shape

(569, 33)

In [120]:
df.drop(["id","Unnamed: 32"], axis=1, inplace=True)
df.head(5)

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [121]:
from sklearn.model_selection import train_test_split

In [122]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [123]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train, X_test

(array([[ 1.25282406,  0.20360051,  1.21782644, ...,  0.50064526,
         -0.87763724, -0.54413099],
        [ 1.39164739,  1.58169742,  1.50506859, ...,  1.03247222,
         -0.9254881 ,  0.42764193],
        [-0.69070258,  0.18762918, -0.66976482, ..., -0.55861465,
          0.44145129, -0.23547584],
        ...,
        [-0.61987435, -0.8459435 , -0.63488541, ..., -0.60058504,
          0.7780023 , -0.26983145],
        [ 0.02041285, -0.27097592, -0.04932178, ..., -0.61603984,
         -0.40710385, -0.40507258],
        [-0.73319952, -0.22762518, -0.76086161, ..., -0.50118946,
          0.50844249, -0.30309641]], shape=(455, 30)),
 array([[ 0.87885101,  0.63254458,  0.90186008, ...,  0.55822197,
          0.28035342, -0.50977538],
        [-0.49238354, -0.67254058, -0.39278132, ...,  0.27639913,
          0.54193809,  1.04767886],
        [-0.46121912, -0.06563035, -0.43094349, ..., -0.35315671,
         -1.2285435 , -0.67119221],
        ...,
        [-0.24023504, -0.79802954, -0

In [124]:
y_train.values

array(['M', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'B',
       'M', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'M', 'B', 'M', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B',
       'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B',
       'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'B',
       'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M',
       'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B

In [125]:
encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

y_train, y_test

(array([1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 

In [127]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)
X_train

tensor([[ 1.2528,  0.2036,  1.2178,  ...,  0.5006, -0.8776, -0.5441],
        [ 1.3916,  1.5817,  1.5051,  ...,  1.0325, -0.9255,  0.4276],
        [-0.6907,  0.1876, -0.6698,  ..., -0.5586,  0.4415, -0.2355],
        ...,
        [-0.6199, -0.8459, -0.6349,  ..., -0.6006,  0.7780, -0.2698],
        [ 0.0204, -0.2710, -0.0493,  ..., -0.6160, -0.4071, -0.4051],
        [-0.7332, -0.2276, -0.7609,  ..., -0.5012,  0.5084, -0.3031]],
       dtype=torch.float64)

In [130]:
X_train = X_train.to(torch.float32)
X_test = X_test.to(torch.float32)
y_train = y_train.to(torch.float32)
y_testt = y_test.to(torch.float32)


In [131]:
X_train.dtype

torch.float32

In [132]:
X_test

tensor([[ 0.8789,  0.6325,  0.9019,  ...,  0.5582,  0.2804, -0.5098],
        [-0.4924, -0.6725, -0.3928,  ...,  0.2764,  0.5419,  1.0477],
        [-0.4612, -0.0656, -0.4309,  ..., -0.3532, -1.2285, -0.6712],
        ...,
        [-0.2402, -0.7980, -0.2434,  ...,  0.8310,  1.0141,  0.9495],
        [-0.0872, -0.7296, -0.1663,  ..., -1.0695, -0.5570, -0.9793],
        [-0.1411, -0.7501, -0.1880,  ..., -0.6983,  0.6887, -0.3914]])

In [133]:
y_train

tensor([1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
        1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
        1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
        0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
        1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
        0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
        1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 

In [134]:
y_test

tensor([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [135]:
from torch.utils.data import Dataset, DataLoader

In [136]:
class CoustemDataset(Dataset):

	def __init__(self, features, label):
		self.features = features
		self.label = label

	def __len__(self):
		return self.features.shape[0]

	def __getitem__(self, index):
		return self.features[index], self.label[index]

In [137]:
train_dataset = CoustemDataset(X_train, y_train)
test_dataset = CoustemDataset(X_test, y_test)

train_dataset

In [138]:
test_dataset.features

tensor([[ 0.8789,  0.6325,  0.9019,  ...,  0.5582,  0.2804, -0.5098],
        [-0.4924, -0.6725, -0.3928,  ...,  0.2764,  0.5419,  1.0477],
        [-0.4612, -0.0656, -0.4309,  ..., -0.3532, -1.2285, -0.6712],
        ...,
        [-0.2402, -0.7980, -0.2434,  ...,  0.8310,  1.0141,  0.9495],
        [-0.0872, -0.7296, -0.1663,  ..., -1.0695, -0.5570, -0.9793],
        [-0.1411, -0.7501, -0.1880,  ..., -0.6983,  0.6887, -0.3914]])

In [139]:
test_dataset.label

tensor([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [140]:
train_loader = DataLoader(train_dataset)
test_loader = DataLoader(test_dataset)

train_loader

In [141]:
test_loader

## Define The Model

In [142]:
import torch.nn as nn

In [143]:
nn

<module 'torch.nn' from 'c:\\Users\\dhruv\\Python_Envs\\dl_env\\lib\\site-packages\\torch\\nn\\__init__.py'>

In [144]:
class my_model(nn.Module):

	def __init__(self,num_feature):

		super().__init__()
		self.linear = nn.Linear(num_feature, 1)
		self.sigmoid = nn.Sigmoid()

	def forward(self, feature):
		out = self.linear(feature)
		out = self.sigmoid(out)

		return out

In [145]:
learning_rate = 0.1
epochs = 25

In [146]:
model = my_model(X_train.shape[1])
model

my_model(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [147]:
optimizer = torch.optim.SGD(model.parameters(), learning_rate)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [148]:
loss_function = nn.BCELoss()
loss_function

BCELoss()

In [149]:
for epoch in range(epochs):
	for batch_f , batch_l in train_loader:
		
		y_pred = model(batch_f)

		## loss calculation
		loss = loss_function(y_pred, batch_l.view(-1,1))

		## clean gradients
		optimizer.zero_grad()
		
		## backpropagation
		loss.backward()
		
		optimizer.step()

		print(f"epoch : {epoch}, loss : {loss.item()}")

epoch : 0, loss : 1.2693231105804443
epoch : 0, loss : 0.761361300945282
epoch : 0, loss : 0.8040226697921753
epoch : 0, loss : 0.6293554306030273
epoch : 0, loss : 0.29506775736808777
epoch : 0, loss : 0.7198396921157837
epoch : 0, loss : 5.674523345078342e-05
epoch : 0, loss : 0.5559072494506836
epoch : 0, loss : 0.026353055611252785
epoch : 0, loss : 0.6828194260597229
epoch : 0, loss : 0.2579222023487091
epoch : 0, loss : 0.06121622771024704
epoch : 0, loss : 1.7737339735031128
epoch : 0, loss : 0.21682481467723846
epoch : 0, loss : 0.08715642988681793
epoch : 0, loss : 1.4250344038009644
epoch : 0, loss : 0.30850955843925476
epoch : 0, loss : 0.01228914875537157
epoch : 0, loss : 0.16097484529018402
epoch : 0, loss : 1.0308843851089478
epoch : 0, loss : 0.42774125933647156
epoch : 0, loss : 0.07352128624916077
epoch : 0, loss : 0.009582689963281155
epoch : 0, loss : 0.04041479527950287
epoch : 0, loss : 0.6470069885253906
epoch : 0, loss : 0.2909655272960663
epoch : 0, loss : 0.07

In [150]:
model.eval()

my_model(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [152]:
accuracy_list = []

with torch.no_grad():

	for batch_feature, batch_label in test_loader:

		y_pred = model(batch_feature)
		y_pred = (y_pred > 0.8).float()
		# print(y_pred)

		batch_accuracy = (y_pred.view(-1) == batch_label).float().mean().item()
		accuracy_list.append(batch_accuracy)

In [153]:
over_all_accuracy = sum(accuracy_list) / len(accuracy_list)
over_all_accuracy

0.9649122807017544

In [154]:
print(f"Accuracy List : {over_all_accuracy}")

Accuracy List : 0.9649122807017544
