In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
print("Dhruv Panchal")

Dhruv Panchal


## lets create one Nural network

In [3]:
import torch
import torch.nn as nn

In [12]:
class Model(nn.Module):
	def __init__(self,num_feature):
		super().__init__()
		
		self.linear = nn.Linear(num_feature, 1)
		self.sigmoid = nn.Sigmoid()

	def forward(self,x):
		
		out = self.linear(x)
		out = self.sigmoid(out)

		return out

In [13]:
features = torch.rand(10,5)
features

tensor([[0.9044, 0.2623, 0.2171, 0.8647, 0.6614],
        [0.4332, 0.3068, 0.5304, 0.4946, 0.0850],
        [0.6215, 0.3477, 0.4960, 0.1252, 0.2550],
        [0.3440, 0.1124, 0.7958, 0.0275, 0.8248],
        [0.1947, 0.5470, 0.6494, 0.0317, 0.7040],
        [0.4121, 0.1192, 0.5797, 0.2290, 0.0050],
        [0.9949, 0.1058, 0.0821, 0.0534, 0.5615],
        [0.3116, 0.2644, 0.0775, 0.9533, 0.8511],
        [0.9486, 0.9034, 0.1366, 0.3636, 0.7837],
        [0.2713, 0.2211, 0.8073, 0.1827, 0.5503]])

In [14]:
## model creation 

model = Model(features.shape[1])

## call model for forward pass
## this is not recommanded 
## it works 
y_pred = model.forward(features)
y_pred

tensor([[0.4977],
        [0.5320],
        [0.5629],
        [0.4564],
        [0.4881],
        [0.5471],
        [0.5802],
        [0.4308],
        [0.5658],
        [0.4721]], grad_fn=<SigmoidBackward0>)

In [15]:
## this is also work
## __call__ this methods is override in the nn class 
## they recommand to use forward pass this way 
y_next = model(features)
y_next

tensor([[0.4977],
        [0.5320],
        [0.5629],
        [0.4564],
        [0.4881],
        [0.5471],
        [0.5802],
        [0.4308],
        [0.5658],
        [0.4721]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear

Linear(in_features=5, out_features=1, bias=True)

In [18]:
model.linear.bias

Parameter containing:
tensor([0.2502], requires_grad=True)

In [20]:
model.linear.weight

Parameter containing:
tensor([[ 0.3304,  0.2054, -0.2533, -0.3186, -0.4259]], requires_grad=True)

In [21]:
## for visualization 
## install torchinfo library

## Visualization

In [22]:
from torchinfo import summary

In [23]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [24]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## lets create a new model with hidden layer

In [45]:
import torch 
import torch.nn as nn
from torchinfo import summary

In [68]:
class Model(nn.Module):
	def __init__(self, num_feature):
		super().__init__()
		self.linear1 = nn.Linear(num_feature,3)
		self.relu = nn.ReLU()
		self.linear2 = nn.Linear(3,1)
		self.sigmoid = nn.Sigmoid()

	def forward(self, x):
		
		out = self.linear1(x)
		out = self.relu(out)
		out = self.linear2(out)
		out = self.sigmoid(out)

		return out

In [69]:
# dummy_data = torch.randint(1,10,(10,5), dtype=torch.float16)
# dummy_data

In [70]:
dummy_data = torch.rand((10,5))
dummy_data

tensor([[0.8216, 0.7674, 0.8839, 0.4770, 0.6772],
        [0.5604, 0.1159, 0.0990, 0.8881, 0.3044],
        [0.8740, 0.9880, 0.9780, 0.6622, 0.4187],
        [0.2343, 0.5500, 0.6387, 0.4644, 0.9166],
        [0.7922, 0.2581, 0.3686, 0.9031, 0.1970],
        [0.0778, 0.7926, 0.1052, 0.4005, 0.8693],
        [0.8564, 0.9225, 0.6027, 0.7984, 0.1790],
        [0.3094, 0.2519, 0.3469, 0.1967, 0.3432],
        [0.7968, 0.4136, 0.2347, 0.6379, 0.5645],
        [0.2921, 0.5423, 0.3252, 0.2269, 0.1817]])

In [71]:
dummy_data.dtype

torch.float32

In [72]:
num_feature = dummy_data.shape[1]
num_feature

5

In [73]:
model = Model(dummy_data.shape[1])
model

Model(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [74]:
y_predict = model(dummy_data)
y_predict

tensor([[0.5137],
        [0.5137],
        [0.5137],
        [0.5130],
        [0.5137],
        [0.5220],
        [0.5137],
        [0.5137],
        [0.5137],
        [0.5137]], grad_fn=<SigmoidBackward0>)

In [75]:
# y_hat = model.forward(dummy_data)

In [76]:
y_hat

tensor([[0.4289],
        [0.4786],
        [0.4468],
        [0.4397],
        [0.4540],
        [0.4717],
        [0.4873],
        [0.4618],
        [0.4564],
        [0.4282]], grad_fn=<SigmoidBackward0>)

In [77]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [78]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [80]:
model.linear1.weight

Parameter containing:
tensor([[-0.1431,  0.4058, -0.4163, -0.0596,  0.0640],
        [ 0.0456,  0.2308, -0.3118, -0.4031, -0.2525],
        [-0.3881,  0.0197,  0.2324, -0.1232,  0.3130]], requires_grad=True)

In [81]:
model.linear1.bias

Parameter containing:
tensor([-0.2394,  0.0115, -0.2856], requires_grad=True)

In [84]:
model.linear2.weight

Parameter containing:
tensor([[ 0.5618, -0.0049, -0.2166]], requires_grad=True)

## Use sequential

In [95]:
import torch 
import torch.nn as nn

In [96]:
class Molde(nn.Module):
	def __init__(self, num_features):
		super().__init__()

		self.network = nn.Sequential(
				nn.Linear(num_features, 3),
				nn.ReLU(),
				nn.Linear(3,1),
				nn.Sigmoid()
				)

	def forward(self, feature):
		result = self.network(feature)
		return result 

In [97]:
Model

__main__.Model

In [98]:
model = Model(5)
model

Model(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [99]:
y_hat = model(dummy_data)
y_hat

tensor([[0.5620],
        [0.5559],
        [0.5766],
        [0.5310],
        [0.5722],
        [0.4934],
        [0.5666],
        [0.5372],
        [0.5532],
        [0.5326]], grad_fn=<SigmoidBackward0>)

In [100]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch 
import torch.nn as nn

In [101]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [102]:
df.drop(columns=["id","Unnamed: 32"], axis=1, inplace=True)
df.shape

(569, 31)

In [103]:
X = df.iloc[:,1:]
y = df.iloc[:,0]
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [105]:
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)
X_train_scale

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]], shape=(455, 30))

In [152]:
X_train_scale = scaler.fit_transform(X_train)
torch.from_numpy(X_train_scale)

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [154]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [156]:
X_train_ten = torch.from_numpy(X_train_scale)
X_test_ten = torch.from_numpy(X_test_scale)
y_train_ten = torch.from_numpy(y_train)
y_test_ten = torch.from_numpy(y_test)
X_train_ten, X_test_ten, y_train_ten, y_test_ten

(tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
         [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
         [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
         ...,
         [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
         [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
         [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
        dtype=torch.float64),
 tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
         [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
         [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
         ...,
         [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
         [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
         [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]],
        dtype=torch.float64),
 tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1

In [158]:
X_train_ten = X_train_ten.to(dtype=torch.float32)
X_test_ten = X_test_ten.to(dtype=torch.float32)
y_train_ten = y_train_ten.to(dtype=torch.float32)
y_test_ten = y_test_ten.to(dtype=torch.float32)
X_train_ten, X_test_ten, y_train_ten, y_test_ten

(tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
         [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
         [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
         ...,
         [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
         [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
         [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]]),
 tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
         [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
         [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
         ...,
         [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
         [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
         [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]]),
 tensor([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
         0., 0., 0., 1., 0., 0., 0.

In [159]:
X_train_ten.dtype

torch.float32

In [160]:
import torch.nn as nn

In [161]:
class my_class(nn.Module):

	def __init__(self,num_feature):
		super().__init__()
		self.linear = nn.Linear(num_feature,1)
		self.sigmoid = nn.Sigmoid()

	def forward(self,x):
		out = self.linear(x)
		out = self.sigmoid(out)

		return out


	def loss_function(self, y_pred, y):
		epsilon = 1e-7
		y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
		loss = -( y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
		return loss

In [162]:
my_class

__main__.my_class

In [163]:
learning_rate = 0.1
epochs = 25

In [166]:
X_train_ten

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]])

In [167]:
X_test_ten

tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
        [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
        [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
        ...,
        [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
        [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
        [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]])

In [168]:
y_train_ten

tensor([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
        0., 1., 1., 0., 1., 1., 0., 0., 

In [169]:
model = my_class(X_train_ten.shape[1])

for i in range(epochs):
	y_predict = model(X_test_ten)

	loss = model.loss_function(y_predict, y_train_ten)
	print(f"epoches : {i} | loss: {loss}")

	loss.backward()

	with torch.no_grad():
		model.linear.weight -= learning_rate * model.linear.weight.grad
		model.linear.bias -= learning_rate * model.linear.bias.grad
	
	model.linear.weight.grad.zero_()
	model.linear.bias.grad.zero_()

epoches : 0 | loss: 0.7447441220283508
epoches : 1 | loss: 0.7380485534667969
epoches : 2 | loss: 0.7321211695671082
epoches : 3 | loss: 0.7268578410148621
epoches : 4 | loss: 0.7221673727035522
epoches : 5 | loss: 0.7179701328277588
epoches : 6 | loss: 0.7141983509063721
epoches : 7 | loss: 0.7107939124107361
epoches : 8 | loss: 0.7077072262763977
epoches : 9 | loss: 0.704896867275238
epoches : 10 | loss: 0.7023274898529053
epoches : 11 | loss: 0.6999691128730774
epoches : 12 | loss: 0.6977969408035278
epoches : 13 | loss: 0.6957895159721375
epoches : 14 | loss: 0.6939287781715393
epoches : 15 | loss: 0.6921995282173157
epoches : 16 | loss: 0.6905885338783264
epoches : 17 | loss: 0.6890843510627747
epoches : 18 | loss: 0.6876774430274963
epoches : 19 | loss: 0.6863589286804199
epoches : 20 | loss: 0.6851215958595276
epoches : 21 | loss: 0.6839587688446045
epoches : 22 | loss: 0.6828645467758179
epoches : 23 | loss: 0.681833803653717
epoches : 24 | loss: 0.6808618307113647


In [170]:
model.linear.weight

Parameter containing:
tensor([[-0.0777,  0.0999,  0.0889, -0.1042,  0.0462,  0.1696,  0.1709, -0.1259,
         -0.0975,  0.0479,  0.1063, -0.1645, -0.1099,  0.0971,  0.0407, -0.0565,
         -0.0499, -0.0796,  0.0606,  0.0144,  0.0126, -0.0489,  0.1198, -0.1148,
         -0.1038, -0.1250,  0.1795, -0.0845, -0.0789, -0.0534]],
       requires_grad=True)

In [171]:
model.linear.bias

Parameter containing:
tensor([-0.1489], requires_grad=True)

In [172]:
class my_class(nn.Module):

	def __init__(self,num_feature):
		super().__init__()
		self.linear = nn.Linear(num_feature,1)
		self.sigmoid = nn.Sigmoid()

	def forward(self,x):
		out = self.linear(x)
		out = self.sigmoid(out)

		return out


In [176]:
## loss function
loss_function = nn.BCELoss()
loss_function

BCELoss()

In [177]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [180]:
y_train_ten.size()

torch.Size([455])

In [182]:
model = my_class(X_train_ten.shape[1])

for i in range(epochs):
	y_predict = model(X_train_ten)
	y_train_ten = y_train_ten.reshape(-1,1)
	loss = loss_function(y_predict, y_train_ten)
	print(f"epoches : {i} | loss: {loss}")

	loss.backward()

	with torch.no_grad():
		model.linear.weight -= learning_rate * model.linear.weight.grad
		model.linear.bias -= learning_rate * model.linear.bias.grad
	
	model.linear.weight.grad.zero_()
	model.linear.bias.grad.zero_()

epoches : 0 | loss: 0.6690189838409424
epoches : 1 | loss: 0.518513560295105
epoches : 2 | loss: 0.43736541271209717
epoches : 3 | loss: 0.3860205411911011
epoches : 4 | loss: 0.3499501049518585
epoches : 5 | loss: 0.32286500930786133
epoches : 6 | loss: 0.3015751242637634
epoches : 7 | loss: 0.2842729985713959
epoches : 8 | loss: 0.2698501944541931
epoches : 9 | loss: 0.2575860321521759
epoches : 10 | loss: 0.24698932468891144
epoches : 11 | loss: 0.2377128154039383
epoches : 12 | loss: 0.22950327396392822
epoches : 13 | loss: 0.2221711277961731
epoches : 14 | loss: 0.21557140350341797
epoches : 15 | loss: 0.2095908671617508
epoches : 16 | loss: 0.2041397988796234
epoches : 17 | loss: 0.1991458237171173
epoches : 18 | loss: 0.19454990327358246
epoches : 19 | loss: 0.19030329585075378
epoches : 20 | loss: 0.1863652616739273
epoches : 21 | loss: 0.1827014982700348
epoches : 22 | loss: 0.1792827546596527
epoches : 23 | loss: 0.1760840266942978
epoches : 24 | loss: 0.17308370769023895


## Evaluate 

In [189]:
with torch.no_grad():
	y_pred = model.forward(X_test_ten)
	y_pred = torch.where(y_pred > 0.5, 1, 0).float()
	accuracy = (y_pred == y_test_ten).float().mean()
	print(f"accuracy : {accuracy.item()}")

accuracy : 0.5280086398124695


In [190]:
class my_class(nn.Module):

	def __init__(self,num_feature):
		super().__init__()
		self.linear = nn.Linear(num_feature,1)
		self.sigmoid = nn.Sigmoid()

	def forward(self,x):
		out = self.linear(x)
		out = self.sigmoid(out)

		return out

In [ ]:
## loss function
loss_function = nn.BCELoss()
loss_function

In [193]:
model = my_class(X_train_ten.shape[1])

## optimizer 
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for i in range(epochs):
	y_predict = model(X_train_ten)
	y_train_ten = y_train_ten.reshape(-1,1)
	loss = loss_function(y_predict, y_train_ten)
	print(f"epoches : {i} | loss: {loss}")

	## clear the gradient 
	optimizer.zero_grad()

	## backward call
	loss.backward()

	## update the model parametes 
	optimizer.step()

epoches : 0 | loss: 0.6902775764465332
epoches : 1 | loss: 0.527301549911499
epoches : 2 | loss: 0.44216886162757874
epoches : 3 | loss: 0.39008891582489014
epoches : 4 | loss: 0.35410383343696594
epoches : 5 | loss: 0.3272951543331146
epoches : 6 | loss: 0.30629628896713257
epoches : 7 | loss: 0.28925031423568726
epoches : 8 | loss: 0.27503880858421326
epoches : 9 | loss: 0.262943297624588
epoches : 10 | loss: 0.2524786591529846
epoches : 11 | loss: 0.24330374598503113
epoches : 12 | loss: 0.2351711094379425
epoches : 13 | loss: 0.22789591550827026
epoches : 14 | loss: 0.22133713960647583
epoches : 15 | loss: 0.21538469195365906
epoches : 16 | loss: 0.20995143055915833
epoches : 17 | loss: 0.2049669772386551
epoches : 18 | loss: 0.20037394762039185
epoches : 19 | loss: 0.196124866604805
epoches : 20 | loss: 0.19218002259731293
epoches : 21 | loss: 0.1885058581829071
epoches : 22 | loss: 0.1850738525390625
epoches : 23 | loss: 0.18185947835445404
epoches : 24 | loss: 0.1788414865732193

In [194]:
with torch.no_grad():
	y_pred = model.forward(X_test_ten)
	y_pred = torch.where(y_pred > 0.5, 1, 0).float()
	accuracy = (y_pred == y_test_ten).float().mean()
	print(f"accuracy : {accuracy.item()}")

accuracy : 0.5301631093025208
