Py-torch

In [ ]:
import torch

In [ ]:
t1 = torch.tensor(4.)

In [ ]:
## single element
t1

tensor(4.)

In [ ]:
t1 = 10

In [ ]:
t1

10

In [ ]:
t1.dtype

AttributeError: 'int' object has no attribute 'dtype'

In [ ]:
type(t1)

int

In [ ]:
## for type
t1.dtype

torch.float32

In [ ]:
t1.numpy()

array(4., dtype=float32)

In [ ]:
t1.shape

torch.Size([])

In [ ]:
t1.size()

torch.Size([])

In [ ]:
## vector
t2 = torch.tensor([1.,2.,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
## metrix
t3 = torch.tensor([[1,2],
                  [3,4.],
                   [5,6]])
print(t3)
print(t3.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.float32


In [ ]:
## 3D tensor
t4 = torch.tensor([[[1,2,3], [3,4,5]],
                    [[2,3,4], [5,6,7.]]
                   ])

In [ ]:
print(t4)
print(type(t4))
print(t4.dtype)
print(t4.shape)

tensor([[[1., 2., 3.],
         [3., 4., 5.]],

        [[2., 3., 4.],
         [5., 6., 7.]]])
<class 'torch.Tensor'>
torch.float32
torch.Size([2, 2, 3])


In [ ]:
print(t4.size())

torch.Size([2, 2, 3])


In [ ]:
print(t4.shape)

torch.Size([2, 2, 3])


In [ ]:
print(t1.shape)
print(t3.shape)
print(t2.shape)

AttributeError: 'int' object has no attribute 'shape'

In [ ]:
t3

In [ ]:
t2

tensor([1., 2., 3., 4.])

In [ ]:
t4

tensor([[[1., 2., 3.],
         [3., 4., 5.]],

        [[2., 3., 4.],
         [5., 6., 7.]]])

In [ ]:
t4.shape

torch.Size([2, 2, 3])

In [ ]:
t = t4.shape

In [ ]:
t4

tensor([[[1., 2., 3.],
         [3., 4., 5.]],

        [[2., 3., 4.],
         [5., 6., 7.]]])

In [ ]:
t4[0][1][0]

tensor(3.)

In [ ]:
t4[1][1][0]


tensor(5.)

In [ ]:
t[0]*t[1]*t[2]

12

In [ ]:
## here you can not  create a ragged matrix, , we  can not  create a tensor with improper size

In [ ]:
t5 = torch.tensor([[5.,6,7],
                   [7,8],
                   [9,7]])
t5

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [ ]:
## we will get an error

In [ ]:
# tennsor oprationn and gradient

In [ ]:
## gradient

In [ ]:
x = torch.tensor(3.)
x

tensor(3.)

In [ ]:
w = torch.tensor(4., requires_grad = True)
w

tensor(4., requires_grad=True)

In [ ]:
b = torch.tensor(5., requires_grad = True)
b

tensor(5., requires_grad=True)

In [ ]:
b = torch.tensor(5, requires_grad = True)
b

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [ ]:
y = (w*x) + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.dtype

torch.float32

In [ ]:
y.backward()

In [ ]:
print("dx/dy : " , x.grad)
print("dw/dy : " , w.grad)
print("db/dy : " , b.grad)

dx/dy :  None
dw/dy :  tensor(3.)
db/dy :  tensor(1.)


In [ ]:
print(x)
w = torch.tensor(4.)
print(w)
b = torch.tensor(5.)
print(b)

tensor(3.)
tensor(4.)
tensor(5.)


In [ ]:
y = w*x + b
y

tensor(17.)

In [ ]:
## if we want to compute gradient of xyz
x.grad()

TypeError: 'NoneType' object is not callable

In [ ]:
y.backward()

## require grad = false

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
##

In [ ]:
#

In [ ]:
### tensor function

In [ ]:
t1 = torch.full((3,2),42)

In [ ]:
## create a constant tensor
t1

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
torch.ones((3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
t2 = torch.tensor([[1,2],
                   [2.,3],
                   [4,5]])

In [ ]:
t2

tensor([[1., 2.],
        [2., 3.],
        [4., 5.]])

In [ ]:
t1

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
## concatenation
t3 = torch.cat([t1,t2],axis = 0)

In [ ]:
t3

tensor([[42., 42.],
        [42., 42.],
        [42., 42.],
        [ 1.,  2.],
        [ 2.,  3.],
        [ 4.,  5.]])

In [ ]:
t4 = torch.cat([t1,t2],axis=1)
t4

tensor([[42., 42.,  1.,  2.],
        [42., 42.,  2.,  3.],
        [42., 42.,  4.,  5.]])

In [ ]:
t5 = torch.sin(t2)
t5

tensor([[ 0.8415,  0.9093],
        [ 0.9093,  0.1411],
        [-0.7568, -0.9589]])

In [ ]:
t3

tensor([[42., 42.],
        [42., 42.],
        [42., 42.],
        [ 1.,  2.],
        [ 2.,  3.],
        [ 4.,  5.]])

In [ ]:
t6 = t3.reshape(3,2,2)

In [ ]:
t6

tensor([[[42., 42.],
         [42., 42.]],

        [[42., 42.],
         [ 1.,  2.]],

        [[ 2.,  3.],
         [ 4.,  5.]]])

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2],[2,3.0]])
x

array([[1., 2.],
       [2., 3.]])

In [ ]:
## convert to tensor
## numpy to tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [2., 3.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [ ]:
## this is a differance


In [ ]:
## tensor to numpy

z = y.numpy()

In [ ]:
z

array([[1., 2.],
       [2., 3.]])

In [ ]:
z.dtype

dtype('float64')

In [ ]:
y.dtype

torch.float64

In [ ]:
import numpy as np
import torch

In [ ]:
## input rainfall, temp, humidity

In [ ]:
input = np.array([[73,67,43],
                  [91,88,64],
                  [87,134,58],
                  [102,43,37],
                  [69,96,70.]], dtype = "float32")
print(input)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]


In [ ]:
## apple , orange
target = np.array([[56,70],
                   [81,101],
                   [119,133],
                   [22,37],
                   [103,119]], dtype="float32")
print(target)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [ ]:
## convert ndarray to tensor

input = torch.from_numpy(input)
target = torch.from_numpy(target)

print(input)

print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
## initalize weights and bias

w  = torch.randn((2,3),requires_grad=True)
b = torch.randn(2 , requires_grad=True)
print(w,b)

tensor([[-1.1093, -1.5308, -0.9423],
        [ 0.4230, -0.3118, -0.0324]], requires_grad=True) tensor([-1.1062,  0.8582], requires_grad=True)


In [ ]:
print(w)

tensor([[-1.1093, -1.5308, -0.9423],
        [ 0.4230, -0.3118, -0.0324]], requires_grad=True)


In [ ]:
print(b)

tensor([-1.1062,  0.8582], requires_grad=True)


In [ ]:
def model(x):
    return ((x @ (w.T)) + b)

predict = model(input)

print(predict)

tensor([[-225.1685,    9.4504],
        [-297.0717,    9.8352],
        [-357.3993,   -6.0032],
        [-214.9430,   29.3931],
        [-290.5685,   -2.1585]], grad_fn=<AddBackward0>)


In [ ]:
w.T

tensor([[-1.1093,  0.4230],
        [-1.5308, -0.3118],
        [-0.9423, -0.0324]], grad_fn=<PermuteBackward0>)

In [ ]:
w.t()

## we convert it into 3 X 2

tensor([[-1.1093,  0.4230],
        [-1.5308, -0.3118],
        [-0.9423, -0.0324]], grad_fn=<TBackward0>)

In [ ]:
input
## 5 X 3

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [ ]:
target
## 5 X 2

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
input @ w.t()

tensor([[-224.0623,    8.5922],
        [-295.9654,    8.9770],
        [-356.2931,   -6.8614],
        [-213.8368,   28.5349],
        [-289.4623,   -3.0167]], grad_fn=<MmBackward0>)

In [ ]:
b

tensor([-1.1062,  0.8582], requires_grad=True)

In [ ]:
input @ w.t() + b

tensor([[-225.1685,    9.4504],
        [-297.0717,    9.8352],
        [-357.3993,   -6.0032],
        [-214.9430,   29.3931],
        [-290.5685,   -2.1585]], grad_fn=<AddBackward0>)

In [ ]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
predict

tensor([[-225.1685,    9.4504],
        [-297.0717,    9.8352],
        [-357.3993,   -6.0032],
        [-214.9430,   29.3931],
        [-290.5685,   -2.1585]], grad_fn=<AddBackward0>)

In [ ]:
def mse(actual,target) :
    diff = actual - target
    return torch.sum(diff*diff)/diff.numel()

In [ ]:
mse(target,predict)

tensor(70602.4766, grad_fn=<DivBackward0>)

In [ ]:
def mse(actual,target) :
    diff = (actual - target)**2
    return torch.sum(diff)/diff.numel()

In [ ]:
loss = mse(target,predict)

In [ ]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
## number of element
target.numel()

10

In [ ]:
loss

tensor(70602.4766, grad_fn=<DivBackward0>)

In [ ]:
loss.backward()

In [ ]:
input.grad

In [ ]:
w.grad

tensor([[-29540.1973, -32783.4492, -20046.9375],
        [ -6789.0459,  -8532.8125,  -5052.5820]])

In [ ]:
b.grad

tensor([-353.2302,  -83.8966])

In [ ]:
## now w zero gradient

In [ ]:
w.grad.zero_()


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
print(w.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
print(w.grad())

TypeError: 'Tensor' object is not callable

In [ ]:
b.grad

tensor([-353.2302,  -83.8966])

In [ ]:
b.grad.zero_()

tensor([0., 0.])

In [ ]:
print(b.grad)

tensor([0., 0.])


In [ ]:
## we do the gradient reset beacuse we do prediction on multiple time

In [ ]:
## adjust parameters

In [ ]:
predict = model(input)

In [ ]:
predict

tensor([[-225.1685,    9.4504],
        [-297.0717,    9.8352],
        [-357.3993,   -6.0032],
        [-214.9430,   29.3931],
        [-290.5685,   -2.1585]], grad_fn=<AddBackward0>)

In [ ]:
loss = mse(target,predict)

In [ ]:
loss

tensor(70602.4766, grad_fn=<DivBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor([[-29540.1973, -32783.4492, -20046.9375],
        [ -6789.0459,  -8532.8125,  -5052.5820]])
tensor([-353.2302,  -83.8966])


In [ ]:
with torch.no_grad():
    w -= w.grad*1e-5
    b -= b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[-0.5185, -0.8752, -0.5414],
        [ 0.5587, -0.1411,  0.0686]], requires_grad=True)
tensor([-1.0992,  0.8599], requires_grad=True)


In [ ]:
pred = model(input)

In [ ]:
pred

tensor([[-120.8626,   35.1433],
        [-159.9425,   43.6780],
        [-194.8783,   34.5403],
        [-111.6455,   54.3216],
        [-158.7861,   30.6687]], grad_fn=<AddBackward0>)

In [ ]:
loss = mse(target,pred)
loss

tensor(29654.3848, grad_fn=<DivBackward0>)

In [ ]:
with torch.no_grad():
    w -= w.grad*1e-5
    b -= b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[-0.5185, -0.8752, -0.5414],
        [ 0.5587, -0.1411,  0.0686]], requires_grad=True)
tensor([-1.0992,  0.8599], requires_grad=True)


In [ ]:
for i in range(100):
    pred = model(input)
    loss = mse(target,pred)
    loss.backward()
    with torch.no_grad():
        w -= w.grad*1e-5
        b -= b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()
    print(f"Epoches {i} and loss {loss}")

Epoches 0 and loss 535.2537231445312
Epoches 1 and loss 528.7781372070312
Epoches 2 and loss 522.3836669921875
Epoches 3 and loss 516.069580078125
Epoches 4 and loss 509.83465576171875
Epoches 5 and loss 503.67791748046875
Epoches 6 and loss 497.59844970703125
Epoches 7 and loss 491.59515380859375
Epoches 8 and loss 485.667236328125
Epoches 9 and loss 479.8135681152344
Epoches 10 and loss 474.03350830078125
Epoches 11 and loss 468.3257751464844
Epoches 12 and loss 462.68963623046875
Epoches 13 and loss 457.12420654296875
Epoches 14 and loss 451.62860107421875
Epoches 15 and loss 446.20184326171875
Epoches 16 and loss 440.84307861328125
Epoches 17 and loss 435.551513671875
Epoches 18 and loss 430.326171875
Epoches 19 and loss 425.1664123535156
Epoches 20 and loss 420.0712890625
Epoches 21 and loss 415.03997802734375
Epoches 22 and loss 410.0716857910156
Epoches 23 and loss 405.1656799316406
Epoches 24 and loss 400.32110595703125
Epoches 25 and loss 395.5372314453125
Epoches 26 and loss 

In [ ]:
print(w)

tensor([[0.0255, 0.7130, 0.2837],
        [0.1930, 0.6505, 0.3812]], requires_grad=True)


In [ ]:
print(b)

tensor([-1.0899,  0.8589], requires_grad=True)


In [ ]:
pred = model(input)
loss = mse(target,pred)
print(loss)

tensor(164.6899, grad_fn=<DivBackward0>)


In [ ]:
from math import sqrt

In [ ]:
sqrt(loss)

12.833156105568218

In [ ]:
pred

tensor([[ 60.7396,  74.9231],
        [ 82.1284, 100.0630],
        [113.1217, 126.9243],
        [ 42.6654,  62.6226],
        [ 88.9734, 103.3075]], grad_fn=<AddBackward0>)

In [ ]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
## neural network using pytorch

In [ ]:
## to check gpu
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch

In [ ]:
from torch import nn

In [ ]:
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt


In [ ]:
training_data = datasets.FashionMNIST(
    root = "data",
    train = True,
    download = True,
    transform= ToTensor()
)

test_data = datasets.FashionMNIST(
    root = "data",
    train = False,
    download = True,
    transform = ToTensor()
)

100%|██████████| 26421880/26421880 [00:01<00:00, 16271163.40it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 266952.93it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:00<00:00, 4985323.04it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 25522786.04it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [ ]:
nn

<module 'torch.nn' from '/usr/local/lib/python3.10/dist-packages/torch/nn/__init__.py'>

In [ ]:
training_data

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [ ]:
test_data

Dataset FashionMNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [ ]:
type(test_data)

torchvision.datasets.mnist.FashionMNIST

In [ ]:
type(training_data)

torchvision.datasets.mnist.FashionMNIST

In [ ]:
batchSize = 64
train_dataloader = DataLoader(training_data,batch_size = batchSize)
test_dataloader = DataLoader(test_data,batch_size = batchSize)

for x,y in test_dataloader:
    print("Shape of X[n,c,h,w] : ",x.shape)
    print("shape od y :",y.shape,y.dtype)
    break

Shape of X[n,c,h,w] :  torch.Size([64, 1, 28, 28])
shape od y : torch.Size([64]) torch.int64


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("we are now using : ",device)

we are now using :  cpu


In [ ]:
# define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork,self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28,512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10)
        )

    def forward(self,x):
        x =self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [ ]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(),lr = 1e-3)

In [ ]:
def train(dataloader,model,loss_fn,optimizer):
    size = len(dataloader.dataset)
    model.train()

    for batch,(x,y) in enumerate(dataloader):
        x,y = x.to(device),y.to(device)

        ## Compute predictoin error
        pre = model(x)
        loss = loss_fn(pre,y)

        ## Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch*100 == 0 :
            loss, current = loss.item(), batch*len(x)
            print(f"loss : {loss:>7f} [ {current:>5d}/{size:>5d}]")


In [ ]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0,0
    with torch.no_grad():
        for x,y in dataloader :
            x, y = x.to(device), y.to(device)
            pred = model(x)
            test_loss += loss_fn(pred,y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error : \n Accuracy : {(100*correct):>0.1f} , Avg loss : {test_loss:>8f} \n")


In [ ]:
epochs = 5
for t in range(epochs):
    print(f"Epochs : {t+1} \n --------------------------")
    train(train_dataloader,model,loss_fn,optimizer)
    test(test_dataloader,model,loss_fn)
print("Done!")

Epochs : 1 
 --------------------------
loss : 2.320918 [     0/60000]
Test Error : 
 Accuracy : 32.5 , Avg loss : 2.154256 

Epochs : 2 
 --------------------------
loss : 2.180183 [     0/60000]
Test Error : 
 Accuracy : 53.3 , Avg loss : 1.883425 

Epochs : 3 
 --------------------------
loss : 1.926408 [     0/60000]
Test Error : 
 Accuracy : 61.5 , Avg loss : 1.519180 

Epochs : 4 
 --------------------------
loss : 1.589477 [     0/60000]
Test Error : 
 Accuracy : 63.6 , Avg loss : 1.257529 

Epochs : 5 
 --------------------------
loss : 1.334977 [     0/60000]
Test Error : 
 Accuracy : 64.5 , Avg loss : 1.094197 

Done!


In [ ]:
## save model
torch.save(model.state_dict(),"model.pth")
print("saved pytorch model state to model.pth")

saved pytorch model state to model.pth


In [ ]:
model = NeuralNetwork()
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [ ]:
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot"
]

model.eval()
x,y = test_data[0][0], test_data[0][1]

with torch.no_grad():
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)],classes[y]
    print(f"predicted : {predicted}, actual : {actual}")


predicted : Ankle boot, actual : Ankle boot


In [1]:
import torch

In [2]:
tensor = torch.tensor([0.1,0.9])
tensor

tensor([0.1000, 0.9000])

In [5]:
samples = torch.multinomial(tensor, num_samples=10, replacement=True)
samples

tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
tensor = torch.tensor([1,2,3,4,5])
out = torch.cat((tensor, torch.tensor([6])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6])

In [9]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [12]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [14]:
out = torch.zeros(5,5).masked_fill(torch.triu(torch.ones(5,5))== 0 , float("-inf"))
out

tensor([[0., 0., 0., 0., 0.],
        [-inf, 0., 0., 0., 0.],
        [-inf, -inf, 0., 0., 0.],
        [-inf, -inf, -inf, 0., 0.],
        [-inf, -inf, -inf, -inf, 0.]])

In [15]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))== 0 , float("-inf"))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [16]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
input = torch.zeros(2,3,4)
input

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
input.shape

torch.Size([2, 3, 4])

In [19]:
out = input.transpose(0,2)
out

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [22]:
out.shape

torch.Size([4, 3, 2])

In [23]:
out1 = input.transpose(0,1)
out1.shape

torch.Size([3, 2, 4])

In [ ]:
## here we pass 0 1 2  are the dimentions
                # 2 3 4
                # 3 2 4
                # 4 3 2


In [20]:
input.T

<ipython-input-20-203fe2415b6a>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3637.)
  input.T


tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [24]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([3,4,5])
tensor3 = torch.tensor([5,6,7])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

## default dim = 0

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [25]:
stacked_tensor = torch.stack([tensor1,tensor2,tensor3],dim=1)
stacked_tensor

tensor([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

In [28]:
import torch.nn as nn

sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)

## linear transformation

print(linear(sample))

tensor([ 6.1224,  4.2115, -4.8187], grad_fn=<SqueezeBackward4>)


In [29]:
linear = nn.Linear(3,1,bias=False)

## linear transformation
## 3 input and second value show the output

print(linear(sample))

tensor([-3.7373], grad_fn=<SqueezeBackward4>)


In [32]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor1,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [33]:
import torch.nn as nn

In [34]:
## Embading

vocab_size = 1000
embedding_size = 100

embedding = nn.Embedding(vocab_size, embedding_size)

input_indices = torch.LongTensor([1,2,3,4])

embedding_output = embedding(input_indices)

print(embedding_output.shape)

torch.Size([4, 100])


In [35]:
embedding_output

tensor([[ 6.7317e-01, -6.0775e-01,  2.2616e-01,  6.4475e-01, -9.5786e-01,
         -1.5392e-01, -6.7305e-01, -1.4680e+00, -6.3673e-01, -4.4504e-02,
         -3.5203e-01, -4.4269e-01, -8.0603e-01,  3.2831e-01, -1.7649e+00,
          1.4208e-01,  9.1895e-02,  1.3067e+00,  2.5802e-01,  1.0116e+00,
          3.8548e-01,  1.7396e+00, -1.3342e+00, -1.4885e+00,  7.5243e-03,
         -1.5530e-01, -3.2763e-01, -1.3537e+00,  2.7955e-01, -5.9710e-01,
          6.3795e-01,  3.0875e-01, -1.4084e+00, -8.1905e-01,  6.9137e-01,
         -1.0777e+00, -2.5954e-01, -2.9294e-01,  1.3602e+00, -1.6316e-02,
          5.9525e-01, -1.3433e+00, -1.0156e-01, -9.4362e-02, -2.5865e+00,
          9.9429e-01,  2.1559e-01,  1.3702e+00,  2.4615e-01, -1.2092e+00,
          1.1740e-01, -1.4320e-02,  9.6165e-01,  1.1600e+00, -5.1184e-01,
          6.7109e-02, -1.8342e-01, -1.6475e+00,  1.0290e+00,  2.2672e+00,
         -3.9259e-02,  3.8998e-01,  5.4569e-01,  7.0658e-01, -1.3195e-01,
          4.2641e-01,  5.7855e-01,  1.

In [36]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,2,3,4,5])

c = torch.dot(a,b)
c

tensor(55)

In [37]:
1+4+9+16+25

55

In [38]:
d = torch.matmul(a,b)
d

tensor(55)

In [39]:
d = a @ b
d

tensor(55)

In [41]:
a = torch.tensor([[1,2] , [3,4]])
b = torch.tensor([[2,2] , [3,3]])
print("a is : ", a)
print("b is : ", b)

a is :  tensor([[1, 2],
        [3, 4]])
b is :  tensor([[2, 2],
        [3, 3]])


In [42]:
a.shape

torch.Size([2, 2])

In [43]:
a.dtype

torch.int64

In [44]:
a.numpy()

array([[1, 2],
       [3, 4]])

In [45]:
torch.dot(a,b)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [46]:
a @ b

tensor([[ 8,  8],
        [18, 18]])

In [47]:
a , b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[2, 2],
         [3, 3]]))

In [48]:
torch.matmul(a,b)

tensor([[ 8,  8],
        [18, 18]])

In [49]:
a_int = torch.randint(1,(3,2))
a_int

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [57]:
torch.randint(2,(3,2))
##           high value # size

tensor([[0, 1],
        [1, 1],
        [0, 0]])

In [58]:
b_float = torch.rand(2,3)
b_float

tensor([[0.4111, 0.5541, 0.3533],
        [0.4947, 0.1088, 0.1031]])

In [59]:
torch.matmul(a_int,b_float)

RuntimeError: expected m1 and m2 to have the same dtype, but got: long int != float

In [60]:
a_int

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [62]:
a_int.dtype

torch.int64

In [61]:
b_float

tensor([[0.4111, 0.5541, 0.3533],
        [0.4947, 0.1088, 0.1031]])

In [63]:
b_float.dtype

torch.float32

In [64]:
a_int.float()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [65]:
torch.matmul(a_int.float(),b_float)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [72]:
sent = "The sun rises in the east"
words = sent.split(" ")
temp = zip(*[words[i:] for i in range(0,2)])
temp

In [74]:
[" ".join(i) for i in temp]

[]

In [73]:
for i in temp:
    print(i)

('The', 'sun')
('sun', 'rises')
('rises', 'in')
('in', 'the')
('the', 'east')


In [80]:
sent = "The sun rises in the east"
words = sent.split(" ")
temp = zip(*[words[i:] for i in range(0,2)])
temp

In [81]:
[" ".join(i) for i in temp]

['The sun', 'sun rises', 'rises in', 'in the', 'the east']