In [1]:
import torch

In [2]:
a = torch.tensor([1,2])
a

tensor([1, 2])

In [3]:
torch.is_tensor(a), torch.is_tensor([1,2])

(True, False)

In [4]:
a.storage()

C:\Users\dhruv\AppData\Local\Temp\ipykernel_29068\214256462.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 1
 2
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 2]

In [6]:
torch.is_storage(a.storage())

True

In [7]:
torch.is_complex(a)

False

In [8]:
b = torch.tensor([1 + 2j, 3 + 1j])
b

tensor([1.+2.j, 3.+1.j])

In [11]:
b_real = b.real
b_complex = b.conj()
b_real, b_complex

(tensor([1., 3.]), tensor([1.-2.j, 3.-1.j]))

In [14]:
b.conj()

tensor([1.-2.j, 3.-1.j])

In [15]:
b_complex_part = b.imag
b_complex_part

tensor([2., 1.])

In [16]:
b_real , b_complex_part, b_complex

(tensor([1., 3.]), tensor([2., 1.]), tensor([1.-2.j, 3.-1.j]))

In [17]:
b

tensor([1.+2.j, 3.+1.j])

In [19]:
torch.is_complex(b), torch.is_complex(b_real), torch.is_complex(b_complex), torch.is_complex(b_complex_part)

(True, False, True, False)

In [20]:
c = torch.tensor([1,2], dtype=torch.int32)
c

tensor([1, 2], dtype=torch.int32)

In [21]:
torch.is_floating_point(b)

False

In [23]:
b_real, torch.is_floating_point(b_real)

(tensor([1., 3.]), True)

In [25]:
c, torch.is_floating_point(c)

(tensor([1, 2], dtype=torch.int32), False)

In [26]:
zero = torch.zeros(2,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
torch.is_nonzero(zero), torch.is_nonzero(b_real)

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

torch.is_nonzero(torch.tensor([1, 2]))  # ❌ RuntimeError: more than one element

In [31]:
torch.is_nonzero(torch.tensor(0)),  torch.is_nonzero(torch.tensor(5)), torch.is_nonzero(torch.tensor(00))

(False, True, False)

In [32]:
torch.is_nonzero(torch.tensor([0]))

False

In [33]:
torch.is_nonzero(torch.tensor([0,0]))

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

⚠️ Only works on scalar tensors. Throws error if tensor has more than one element.

In [44]:
# Sets the default floating-point type used in tensor creation when not explicitly set.


torch.set_default_dtype(torch.float64)

In [45]:
x = torch.tensor([1.0])
x

tensor([1.])

In [46]:
y = torch.tensor([1,2])
y

tensor([1, 2])

In [47]:
x.dtype,y.dtype

(torch.float64, torch.int64)

In [48]:
x = torch.tensor([1.0], dtype=torch.float32)
x.dtype

torch.float32

In [50]:
# Sets the default floating-point type used in tensor creation when not explicitly set.


torch.set_default_dtype(torch.float32)
x = torch.tensor([1.0])
print(x.dtype)

torch.float32


In [52]:
torch.get_default_dtype()

torch.float32

In [54]:
torch.get_default_device()

device(type='cpu')

In [55]:
torch.set_default_tensor_type(torch.FloatTensor)## used for cpu

a = torch.tensor([1,2])
a, a.dtype, a.ndim

c:\Users\dhruv\Python_Envs\dl_env\lib\site-packages\torch\__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\tensor\python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)


(tensor([1, 2]), torch.int64, 1)

In [56]:
a = torch.tensor([1.0,2])
a, a.dtype, a.ndim, a.device, a.shape

(tensor([1., 2.]), torch.float32, 1, device(type='cpu'), torch.Size([2]))

In [57]:
torch.set_default_tensor_type(torch.cuda.FloatTensor)## used for GPU
a = torch.tensor([1.0,2])
a, a.dtype, a.ndim, a.device, a.shape

TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

In [ ]:
torch.set_default_tensor_type(torch.cuda.FloatTensor)
x = torch.tensor([1.0])  # created directly on GPU

📊 Tensor Metadata & Debuggingm

In [59]:
a = torch.tensor([1,2])
a

tensor([1, 2])

In [60]:
a, a.dtype, a.shape, a.ndim

(tensor([1, 2]), torch.int64, torch.Size([2]), 1)

In [61]:
x = torch.randn(3,4)
x

tensor([[ 0.2190,  0.1221, -0.5958,  0.3178],
        [-0.6745, -0.1970,  0.7593,  1.4676],
        [ 0.3012, -0.7419, -0.2515,  0.5216]])

In [62]:
torch.numel(x)

12

In [63]:
x.shape

torch.Size([3, 4])

In [64]:
## lets set some printing options

torch.set_printoptions(precision=2, sci_mode=False)

x = torch.tensor([3.1244666])
x

tensor([3.12])

In [65]:
x.item()

3.12446665763855

In [66]:
print(x)

tensor([3.12])


Options include:

precision: digits after the decimal

sci_mode: enable/disable scientific notation

threshold: total elements before summarizing

linewidth: max characters per line

In [67]:
# Flusing 
# Why? CPUs are slow when working with very tiny floating-point values (like 1e-308). Flushing avoids that slowdown.


In [79]:
torch.set_printoptions(precision= None)

In [80]:
torch.set_flush_denormal(True)


True

In [81]:
el1 = torch.tensor(1328763.e-8)
el1

tensor(0.01)

In [82]:
torch.set_flush_denormal(False)
el1 = torch.tensor(1328763.e-8)
el1

tensor(0.01)

In [83]:
torch.set_printoptions(profile="default") ## to set back to normal 

In [84]:
torch.set_flush_denormal(False)
el1 = torch.tensor(1328763.e-8)
el1

tensor(0.0133)

In [85]:
torch.set_flush_denormal(True)

el1 = torch.tensor(1328763.e-8)
el1

tensor(0.0133)

# Creation Ops


In [86]:
# torch.tensor(data)
# Creates a new tensor by copying the data.

# No autograd history by default → a leaf tensor.

# Preserves dtype if given, or infers it from the data.


In [88]:
a = torch.tensor([1,2])
a.dtype, a.device

(torch.int64, device(type='cpu'))

In [89]:
a = torch.tensor([1,2], dtype=torch.float64)
a.dtype, a.device

(torch.float64, device(type='cpu'))

In [90]:
# ✅ Use when: converting Python lists to PyTorch tensors.

# 🧠 Hidden Tip: Avoid wrapping a tensor again:
# torch.tensor(torch.tensor([1])) → BAD (copies data again!)

b = a
b

tensor([1., 2.], dtype=torch.float64)

In [91]:
b[0] = 0

In [92]:
b

tensor([0., 2.], dtype=torch.float64)

In [93]:
a

tensor([0., 2.], dtype=torch.float64)

In [94]:
## that why clone

c = a.clone()
c

tensor([0., 2.], dtype=torch.float64)

In [95]:
c[0] = 1
c, a

(tensor([1., 2.], dtype=torch.float64), tensor([0., 2.], dtype=torch.float64))

In [97]:
a = torch.tensor([1,2,3], dtype=torch.float64,requires_grad=True)

b = a.detach()
a, b

(tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True),
 tensor([1., 2., 3.], dtype=torch.float64))

In [98]:
b[0] = 0
b,a

(tensor([0., 2., 3.], dtype=torch.float64),
 tensor([0., 2., 3.], dtype=torch.float64, requires_grad=True))

In [99]:
c = a.clone().detach()
c[0] = 10
c,a,

(tensor([10.,  2.,  3.], dtype=torch.float64),
 tensor([0., 2., 3.], dtype=torch.float64, requires_grad=True))

In [100]:
# 1. Using clone()

# Creates a deep copy of the tensor with its own memory.

# Changes to the copied tensor do not affect the original.

# Keeps the computation graph intact (useful when gradients are tracked).

# 2. Using detach()

# Creates a tensor that shares data with the original but is detached from the computation graph.

# Useful when you want a tensor copy for inference or analysis without tracking gradients.

# Changes to the detached tensor affect the original data since they share storage.



In [101]:
import numpy as np 

arr = np.array([1,2])
arr

array([1, 2])

In [102]:
t = torch.as_tensor(arr)
t

tensor([1, 2], dtype=torch.int32)

In [104]:
back = torch.asarray(arr)
back

tensor([1, 2], dtype=torch.int32)

In [103]:
back = torch.asarray(t)
back

tensor([1, 2], dtype=torch.int32)

In [105]:
# Sparse Tensor Creation

In [106]:
# Sparse tensors save memory for data with lots of zeros. PyTorch supports multiple formats:

# 🧵 sparse_coo_tensor(indices, values, size)
# COO = Coordinate format. Most flexible and commonly used sparse format

In [107]:
i  = torch.tensor([[0,1], [2,0]])
v = torch.tensor([3,4])

sparse = torch.sparse_coo_tensor(i,v,(2,3))
sparse

tensor(indices=tensor([[0, 1],
                       [2, 0]]),
       values=tensor([3, 4]),
       size=(2, 3), nnz=2, layout=torch.sparse_coo)

In [108]:
a = np.array([1,2,4])
b = torch.from_numpy(a)
b

tensor([1, 2, 4], dtype=torch.int32)

In [109]:
one = torch.ones(3,4)
zero = torch.zeros(4,5)
one, zero

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]))

In [110]:
one.shape, zero.shape

(torch.Size([3, 4]), torch.Size([4, 5]))

In [111]:
of3 = torch.full((4,5), 3)
of3

tensor([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]])

In [112]:
a = torch.randn(3,4)
a.shape

torch.Size([3, 4])

In [113]:
## i want to create same tensor like a 

b = torch.zeros_like(a)
c = torch.ones_like(a)
b, c

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [114]:
b.shape, c.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [115]:
z = torch.empty(2,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
d = torch.arange(2, 5, 10)
d

tensor([2])

In [117]:
d = torch.arange(2, 5, 0.10)
d

tensor([2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000, 2.7000, 2.8000,
        2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000, 3.7000,
        3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000, 4.5000, 4.6000,
        4.7000, 4.8000, 4.9000])

In [119]:
d.shape

torch.Size([30])

In [124]:
c = torch.range(1,3,1)
c

C:\Users\dhruv\AppData\Local\Temp\ipykernel_29068\615080746.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  c = torch.range(1,3,1)


tensor([1., 2., 3.])

In [125]:
## line space

l1 = torch.linspace(2,10,5)
l1.shape

torch.Size([5])

In [127]:
l2  = torch.logspace(1,10,3 , base=10)
l2.shape, l2

(torch.Size([3]), tensor([1.0000e+01, 3.1623e+05, 1.0000e+10]))

In [128]:
l2  = torch.logspace(1,10,3 , base=2)
l2.shape, l2

(torch.Size([3]), tensor([   2.0000,   45.2548, 1024.0000]))

In [129]:
l2  = torch.logspace(1,10,3 , base=1)
l2.shape, l2

(torch.Size([3]), tensor([1., 1., 1.]))

In [130]:
i = torch.eye(4)
i.shape, i

(torch.Size([4, 4]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]))

In [133]:
h = torch.eye(4,6)
h.shape, h

(torch.Size([4, 6]),
 tensor([[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.]]))

In [ ]:
## permutation 


torch.randperm(5)

tensor([2, 4, 3, 1, 0])

In [137]:
## permutation 


torch.randperm((5,6))

TypeError: randperm(): argument 'n' (position 1) must be int, not tuple

In [139]:
torch.randperm(10)

# randperm(n)
# Random permutation of integers [0, n).

tensor([5, 8, 3, 4, 0, 1, 2, 7, 6, 9])

In [140]:
x = torch.tensor([1.0,2.0,3.0])

x

tensor([1., 2., 3.])

In [141]:
q = torch.quantize_per_tensor(x, scale=0.1,zero_point=0, dtype=torch.qint8)
q

tensor([1., 2., 3.], size=(3,), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=0)

In [142]:
dq = q.dequantize()
dq

tensor([1., 2., 3.])

In [145]:
## lets make complex tensor 

c = torch.complex(torch.tensor([1.,2]), torch.tensor([3.,4]))
c

tensor([1.+3.j, 2.+4.j])

In [146]:
## in complex we have to pass both term real and complex 

In [148]:
# 🔮 polar(abs, angle)

In [150]:
import math

torch.polar(torch.tensor([1.0]), torch.tensor([math.pi/2]))

tensor([-4.3711e-08+1.j])

In [151]:
ar = torch.empty(2,4)
ar

tensor([[0.0000, 0.0000, 0.0000, 2.0000],
        [0.0000, 2.1250, 0.0000, 0.0000]])

In [152]:
arr = torch.empty(3,4).normal_()
arr

tensor([[ 0.7298,  1.0862,  0.1710, -0.5972],
        [-0.1941, -0.9330,  0.8638,  0.5396],
        [-0.1360, -1.2374,  0.6117,  0.6956]])

In [153]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [154]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [156]:
torch.eye(4) @ torch.eye(4)  #### identity multiplicity 

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [157]:
### 
x = torch.arange(9).reshape(3,3)
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [160]:
y = torch.as_strided(x,(3,3),(1,3))
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [161]:
y = torch.as_strided(x,(2,2),(1,3))
y

tensor([[0, 3],
        [1, 4]])

In [162]:
## low Memory grid creation 

In [164]:
x = torch.linspace(-1,1,5)
y = torch.linspace(-1,1,5)

grid_x, grid_y = torch.meshgrid(x, y, indexing="ij")
grid_x, grid_y

(tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
         [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.5000,  0.5000,  0.5000,  0.5000,  0.5000],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000]]),
 tensor([[-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000]]))

In [165]:
grid_x.shape, grid_y.shape

(torch.Size([5, 5]), torch.Size([5, 5]))

In [166]:
torch.manual_seed(42)


In [167]:
indices  = torch.randperm(5)
indices

tensor([2, 4, 3, 0, 1])

In [168]:
torch.arange(16).reshape(2,2,2,2)


tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])

In [169]:
mask = torch.full((5,5), float("inf"))
mask

tensor([[inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf]])

In [171]:
mask = torch.full((5,5), float("-inf"))
mask

tensor([[-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf]])

In [172]:
labels = torch.tensor([0,2,1])

labels 

tensor([0, 2, 1])

In [173]:
one_hot = torch.nn.functional.one_hot(labels, num_classes=3)
one_hot

tensor([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]])

# Indexing, Slicing, Joining, Mutating Ops

In [176]:
x = torch.tensor([[1+2j, 3+4j]], dtype= torch.complex64)
x

tensor([[1.+2.j, 3.+4.j]])

In [ ]:
print(x.adjoint()) # # Conjugate + transpose (for matrices)


tensor([[1.-2.j],
        [3.-4.j]])


In [178]:
x.shape

torch.Size([1, 2])

In [179]:
y = x.adjoint()
y.shape, y

(torch.Size([2, 1]),
 tensor([[1.-2.j],
         [3.-4.j]]))

In [181]:
t = torch.tensor([[0,1],[2,0.0]])
t

tensor([[0., 1.],
        [2., 0.]])

In [182]:
torch.argwhere(t)

tensor([[0, 1],
        [1, 0]])

In [183]:
print(torch.argwhere(t))

tensor([[0, 1],
        [1, 0]])


In [184]:
## indices of non zero elements 

In [185]:
a = torch.tensor([[1,2]])
b = torch.tensor([[3,4]])
a,b

(tensor([[1, 2]]), tensor([[3, 4]]))

In [186]:
torch.cat((a,b), dim=0)

tensor([[1, 2],
        [3, 4]])

In [187]:
torch.cat((a,b), dim=1)

tensor([[1, 2, 3, 4]])

In [188]:
a.shape, b.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [189]:
x = torch.tensor([1+2j, 3+4j])
x

tensor([1.+2.j, 3.+4.j])

In [190]:
x.conj()

tensor([1.-2.j, 3.-4.j])

In [191]:
## concate, concatenate, cat all are same

In [192]:
x = torch.arange(8)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [194]:
torch.chunk(x,4) # Attempts to split a tensor into the specified number of chunks.

(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]))

In [195]:
torch.chunk(x,2)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]))

In [197]:
arr = torch.randn(3,4)
arr

tensor([[ 0.2345,  0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898]])

In [198]:
torch.chunk(arr, 2)

(tensor([[ 0.2345,  0.2303, -1.1229, -0.1863],
         [ 2.2082, -0.6380,  0.4617,  0.2674]]),
 tensor([[ 0.5349,  0.8094,  1.1103, -1.6898]]))

In [200]:
torch.chunk(arr, 2, dim=1)

(tensor([[ 0.2345,  0.2303],
         [ 2.2082, -0.6380],
         [ 0.5349,  0.8094]]),
 tensor([[-1.1229, -0.1863],
         [ 0.4617,  0.2674],
         [ 1.1103, -1.6898]]))

In [201]:
arr = torch.randn(2,3,4)
arr

tensor([[[-1.1109,  0.0915, -2.3169, -0.2168],
         [-1.3847, -0.8712, -0.2234,  1.7174],
         [-0.4880,  1.1914, -0.8140, -0.7360]],

        [[-0.8371, -0.9224,  1.8113,  0.1606],
         [-0.0978,  1.8446, -1.1845,  1.3835],
         [-1.2024,  0.7078, -1.0759,  0.5357]]])

In [204]:
torch.chunk(arr, 4, dim=-1)

(tensor([[[-1.1109],
          [-1.3847],
          [-0.4880]],
 
         [[-0.8371],
          [-0.0978],
          [-1.2024]]]),
 tensor([[[ 0.0915],
          [-0.8712],
          [ 1.1914]],
 
         [[-0.9224],
          [ 1.8446],
          [ 0.7078]]]),
 tensor([[[-2.3169],
          [-0.2234],
          [-0.8140]],
 
         [[ 1.8113],
          [-1.1845],
          [-1.0759]]]),
 tensor([[[-0.2168],
          [ 1.7174],
          [-0.7360]],
 
         [[ 0.1606],
          [ 1.3835],
          [ 0.5357]]]))

In [ ]:
torch.chunk(arr, 4, dim=0)

(tensor([[[-1.1109,  0.0915, -2.3169, -0.2168],
          [-1.3847, -0.8712, -0.2234,  1.7174],
          [-0.4880,  1.1914, -0.8140, -0.7360]]]),
 tensor([[[-0.8371, -0.9224,  1.8113,  0.1606],
          [-0.0978,  1.8446, -1.1845,  1.3835],
          [-1.2024,  0.7078, -1.0759,  0.5357]]]))

In [208]:
arr.shape

torch.Size([2, 3, 4])

In [207]:
torch.chunk(arr, 4, dim=1) , len(torch.chunk(arr, 4, dim=1))

((tensor([[[-1.1109,  0.0915, -2.3169, -0.2168]],
  
          [[-0.8371, -0.9224,  1.8113,  0.1606]]]),
  tensor([[[-1.3847, -0.8712, -0.2234,  1.7174]],
  
          [[-0.0978,  1.8446, -1.1845,  1.3835]]]),
  tensor([[[-0.4880,  1.1914, -0.8140, -0.7360]],
  
          [[-1.2024,  0.7078, -1.0759,  0.5357]]])),
 3)

In [210]:
arr

tensor([[[-1.1109,  0.0915, -2.3169, -0.2168],
         [-1.3847, -0.8712, -0.2234,  1.7174],
         [-0.4880,  1.1914, -0.8140, -0.7360]],

        [[-0.8371, -0.9224,  1.8113,  0.1606],
         [-0.0978,  1.8446, -1.1845,  1.3835],
         [-1.2024,  0.7078, -1.0759,  0.5357]]])

In [211]:
torch.chunk(arr, 4, dim=2) , len(torch.chunk(arr, 4, dim=2))

((tensor([[[-1.1109],
           [-1.3847],
           [-0.4880]],
  
          [[-0.8371],
           [-0.0978],
           [-1.2024]]]),
  tensor([[[ 0.0915],
           [-0.8712],
           [ 1.1914]],
  
          [[-0.9224],
           [ 1.8446],
           [ 0.7078]]]),
  tensor([[[-2.3169],
           [-0.2234],
           [-0.8140]],
  
          [[ 1.8113],
           [-1.1845],
           [-1.0759]]]),
  tensor([[[-0.2168],
           [ 1.7174],
           [-0.7360]],
  
          [[ 0.1606],
           [ 1.3835],
           [ 0.5357]]])),
 4)

In [212]:
## Dsplit, hsplit, vsplit

In [217]:
x = torch.arange(27).reshape(3,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [215]:
print(torch.dsplit(x,3))

RuntimeError: torch.dsplit requires a tensor with at least 3 dimension, but got a tensor with 2 dimensions!

In [218]:
print(torch.dsplit(x,3))

(tensor([[[ 0],
         [ 3],
         [ 6]],

        [[ 9],
         [12],
         [15]],

        [[18],
         [21],
         [24]]]), tensor([[[ 1],
         [ 4],
         [ 7]],

        [[10],
         [13],
         [16]],

        [[19],
         [22],
         [25]]]), tensor([[[ 2],
         [ 5],
         [ 8]],

        [[11],
         [14],
         [17]],

        [[20],
         [23],
         [26]]]))


In [220]:
x1,x2,x3  = torch.dsplit(x,3)
x1, x1.shape

(tensor([[[ 0],
          [ 3],
          [ 6]],
 
         [[ 9],
          [12],
          [15]],
 
         [[18],
          [21],
          [24]]]),
 torch.Size([3, 3, 1]))

In [222]:
x2, x2.shape

(tensor([[[ 1],
          [ 4],
          [ 7]],
 
         [[10],
          [13],
          [16]],
 
         [[19],
          [22],
          [25]]]),
 torch.Size([3, 3, 1]))

In [223]:
x3, x3.shape

(tensor([[[ 2],
          [ 5],
          [ 8]],
 
         [[11],
          [14],
          [17]],
 
         [[20],
          [23],
          [26]]]),
 torch.Size([3, 3, 1]))

In [225]:
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [224]:
print(torch.hsplit(x,3))

(tensor([[[ 0,  1,  2]],

        [[ 9, 10, 11]],

        [[18, 19, 20]]]), tensor([[[ 3,  4,  5]],

        [[12, 13, 14]],

        [[21, 22, 23]]]), tensor([[[ 6,  7,  8]],

        [[15, 16, 17]],

        [[24, 25, 26]]]))


In [226]:
print(torch.vsplit(x,3))

(tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]), tensor([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]), tensor([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]))


In [241]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
a,b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [242]:
torch.column_stack((a,b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [243]:
torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [230]:
torch.hstack((a,b))

tensor([1, 2, 3, 4, 5, 6])

In [244]:
torch.dstack((a,b))

tensor([[[1, 4],
         [2, 5],
         [3, 6]]])

In [237]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([[4,5,6]])
a,b

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]))

In [238]:
torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [239]:
torch.hstack((a,b))

tensor([[1, 2, 3, 4, 5, 6]])

In [240]:
torch.dstack((a,b))

tensor([[[1, 4],
         [2, 5],
         [3, 6]]])

In [235]:
a.shape, b.shape, torch.hstack((a,b)).shape

(torch.Size([1, 3]), torch.Size([1, 3]), torch.Size([1, 6]))

In [236]:
torch.dstack((a,b))

tensor([[[1, 4],
         [2, 5],
         [3, 6]]])

## gather

In [245]:
t = torch.tensor([[1,2],[3,4]])
index = torch.tensor([[0,1],[1,0]])
t, index

(tensor([[1, 2],
         [3, 4]]),
 tensor([[0, 1],
         [1, 0]]))

In [248]:
torch.gather(t, 1, index)

tensor([[1, 2],
        [4, 3]])

In [253]:
# input: The source tensor from which values are gathered.

# dim: The dimension along which to gather values.

# index: A tensor of indices specifying which elements to select from input along the given dimension.

# Output:
# The output tensor has the same shape as the index tensor. Each element in the output is taken from the input tensor at the position specified by the corresponding index along the dimension dim.

In [252]:
torch.gather(t, 0, index)

tensor([[1, 4],
        [3, 2]])

In [254]:
# --- 9. index_select / masked_select ---

In [255]:
t = torch.tensor([[1,2],[3,4]])
t

tensor([[1, 2],
        [3, 4]])

In [256]:
## select some index 

torch.index_select(t,1,torch.tensor(0))

tensor([[1],
        [3]])

In [263]:
## select some index 

## tensor, dimension, index tensor 
torch.index_select(t,1, torch.tensor([0]) ), torch.index_select(t,1, torch.tensor([0,1]) ) 

(tensor([[1],
         [3]]),
 tensor([[1, 2],
         [3, 4]]))

In [261]:
torch.masked_select(t, t>2)

tensor([3, 4])

In [264]:
ar = torch.randn(2,4,3,5)
ar

tensor([[[[ 3.4665e-01, -1.9733e-01, -1.0546e+00,  1.2780e+00,  1.4534e-01],
          [ 2.3105e-01,  8.6540e-03, -1.4229e-01,  5.7501e-01, -6.4172e-01],
          [-2.2064e+00, -7.5080e-01,  2.8140e+00,  3.5979e-01, -8.9808e-02]],

         [[ 4.5844e-01,  5.3619e-01,  5.2462e-01,  1.1412e+00,  5.1644e-02],
          [ 7.2811e-01, -7.1064e-01, -6.0207e-01,  9.6045e-01, -1.7223e+00],
          [-8.2777e-01,  1.3347e+00,  4.8354e-01, -1.9756e-01,  1.2683e+00]],

         [[ 1.2243e+00,  9.8117e-02,  6.4076e-01,  5.8325e-01,  1.0669e+00],
          [-4.5015e-01, -6.7875e-01,  5.7432e-01,  1.8775e-01, -3.5762e-01],
          [ 2.6491e-01,  1.2732e+00, -1.3109e-03, -3.0360e-01, -9.8644e-01]],

         [[ 1.2330e-01,  3.4987e-01,  6.1728e-01,  7.2618e-01,  9.1152e-02],
          [-3.8907e-01,  5.2792e-01,  1.0311e+00, -7.0477e-01,  1.0131e+00],
          [-3.3082e-01,  1.0950e+00,  3.3989e-01,  7.1997e-01,  4.1141e-01]]],


        [[[-5.7332e-01,  5.0686e-01, -4.7521e-01, -4.9203e-01, -1.

In [266]:
torch.masked_select(ar, ar > 1)

tensor([1.2780, 2.8140, 1.1412, 1.3347, 1.2683, 1.2243, 1.0669, 1.2732, 1.0311,
        1.0131, 1.0950, 1.6354, 1.0331, 1.0414, 1.1179, 1.7744, 2.1120])

In [267]:
## move dimensions, axis

ar

tensor([[[[ 3.4665e-01, -1.9733e-01, -1.0546e+00,  1.2780e+00,  1.4534e-01],
          [ 2.3105e-01,  8.6540e-03, -1.4229e-01,  5.7501e-01, -6.4172e-01],
          [-2.2064e+00, -7.5080e-01,  2.8140e+00,  3.5979e-01, -8.9808e-02]],

         [[ 4.5844e-01,  5.3619e-01,  5.2462e-01,  1.1412e+00,  5.1644e-02],
          [ 7.2811e-01, -7.1064e-01, -6.0207e-01,  9.6045e-01, -1.7223e+00],
          [-8.2777e-01,  1.3347e+00,  4.8354e-01, -1.9756e-01,  1.2683e+00]],

         [[ 1.2243e+00,  9.8117e-02,  6.4076e-01,  5.8325e-01,  1.0669e+00],
          [-4.5015e-01, -6.7875e-01,  5.7432e-01,  1.8775e-01, -3.5762e-01],
          [ 2.6491e-01,  1.2732e+00, -1.3109e-03, -3.0360e-01, -9.8644e-01]],

         [[ 1.2330e-01,  3.4987e-01,  6.1728e-01,  7.2618e-01,  9.1152e-02],
          [-3.8907e-01,  5.2792e-01,  1.0311e+00, -7.0477e-01,  1.0131e+00],
          [-3.3082e-01,  1.0950e+00,  3.3989e-01,  7.1997e-01,  4.1141e-01]]],


        [[[-5.7332e-01,  5.0686e-01, -4.7521e-01, -4.9203e-01, -1.

In [268]:
ar.shape

torch.Size([2, 4, 3, 5])

In [269]:
ar.size()

torch.Size([2, 4, 3, 5])

In [271]:
torch.movedim(ar, -1, -2).shape

torch.Size([2, 4, 5, 3])

In [272]:
torch.movedim(ar, 0, 1).shape

torch.Size([4, 2, 3, 5])

In [277]:
torch.movedim(ar, 0, 2).shape

torch.Size([4, 3, 2, 5])

In [273]:
ar.shape, torch.moveaxis(ar, 0,1).shape

(torch.Size([2, 4, 3, 5]), torch.Size([4, 2, 3, 5]))

In [275]:
ar.shape

torch.Size([2, 4, 3, 5])

In [274]:
torch.moveaxis(ar, 1,3).shape

torch.Size([2, 3, 5, 4])

In [ ]:
torch.moveaxis(ar, 0,1).shape

In [276]:
ar.shape, torch.moveaxis(ar, 0,1).shape

(torch.Size([2, 4, 3, 5]), torch.Size([4, 2, 3, 5]))

In [278]:
## this move dim and move axis its just move the dim do not swap the dimensiton 

In [281]:
# Purpose: Creates a view (not a copy) of the original tensor t along dimension 0 (rows), starting at index 2 and selecting 4 elements.

In [279]:
t = torch.arange(10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [280]:
t.shape, torch.narrow(t, 0, 2, 4)

(torch.Size([10]), tensor([2, 3, 4, 5]))

In [283]:
ar = torch.randn(2,3,4)

torch.narrow(ar, 0, 0, 1)

tensor([[[-0.8719, -0.0271, -0.3532,  1.4639],
         [ 0.1729,  1.0514,  0.0075, -0.0774],
         [ 0.8351, -0.3157,  0.2691,  0.0854]]])

In [284]:
ar

tensor([[[-8.7189e-01, -2.7118e-02, -3.5325e-01,  1.4639e+00],
         [ 1.7290e-01,  1.0514e+00,  7.4915e-03, -7.7365e-02],
         [ 8.3509e-01, -3.1571e-01,  2.6911e-01,  8.5404e-02]],

        [[-1.3793e+00,  6.2580e-01, -2.5850e+00, -2.4000e-02],
         [ 5.2394e-01, -2.6935e-01, -1.6191e+00,  1.2588e-03],
         [ 1.1930e+00,  1.9373e+00,  7.2871e-01,  9.8089e-01]]])

In [285]:
ar.ndim

3

In [287]:
ar, ar.shape

(tensor([[[-8.7189e-01, -2.7118e-02, -3.5325e-01,  1.4639e+00],
          [ 1.7290e-01,  1.0514e+00,  7.4915e-03, -7.7365e-02],
          [ 8.3509e-01, -3.1571e-01,  2.6911e-01,  8.5404e-02]],
 
         [[-1.3793e+00,  6.2580e-01, -2.5850e+00, -2.4000e-02],
          [ 5.2394e-01, -2.6935e-01, -1.6191e+00,  1.2588e-03],
          [ 1.1930e+00,  1.9373e+00,  7.2871e-01,  9.8089e-01]]]),
 torch.Size([2, 3, 4]))

In [291]:
torch.narrow(ar, 1, 0, 2)

tensor([[[-8.7189e-01, -2.7118e-02, -3.5325e-01,  1.4639e+00],
         [ 1.7290e-01,  1.0514e+00,  7.4915e-03, -7.7365e-02]],

        [[-1.3793e+00,  6.2580e-01, -2.5850e+00, -2.4000e-02],
         [ 5.2394e-01, -2.6935e-01, -1.6191e+00,  1.2588e-03]]])

In [293]:
torch.narrow(ar, 1, 0, 1).shape

torch.Size([2, 1, 4])

In [294]:
torch.narrow(ar, 1, 0, 2).shape

torch.Size([2, 2, 4])

In [295]:
ar, ar.shape

(tensor([[[-8.7189e-01, -2.7118e-02, -3.5325e-01,  1.4639e+00],
          [ 1.7290e-01,  1.0514e+00,  7.4915e-03, -7.7365e-02],
          [ 8.3509e-01, -3.1571e-01,  2.6911e-01,  8.5404e-02]],
 
         [[-1.3793e+00,  6.2580e-01, -2.5850e+00, -2.4000e-02],
          [ 5.2394e-01, -2.6935e-01, -1.6191e+00,  1.2588e-03],
          [ 1.1930e+00,  1.9373e+00,  7.2871e-01,  9.8089e-01]]]),
 torch.Size([2, 3, 4]))

In [297]:
torch.narrow(ar, 2, 0 ,1), torch.narrow(ar, 2, 0 ,1).shape 

(tensor([[[-0.8719],
          [ 0.1729],
          [ 0.8351]],
 
         [[-1.3793],
          [ 0.5239],
          [ 1.1930]]]),
 torch.Size([2, 3, 1]))

In [298]:
torch.narrow(ar, 2, 0 ,2), torch.narrow(ar, 2, 0 ,2).shape

(tensor([[[-0.8719, -0.0271],
          [ 0.1729,  1.0514],
          [ 0.8351, -0.3157]],
 
         [[-1.3793,  0.6258],
          [ 0.5239, -0.2694],
          [ 1.1930,  1.9373]]]),
 torch.Size([2, 3, 2]))

In [ ]:
torch.narrow(ar, 2, 0 , 3), torch.narrow(ar, 2, 0 , 3).shape

(tensor([[[-0.8719, -0.0271, -0.3532],
          [ 0.1729,  1.0514,  0.0075],
          [ 0.8351, -0.3157,  0.2691]],
 
         [[-1.3793,  0.6258, -2.5850],
          [ 0.5239, -0.2694, -1.6191],
          [ 1.1930,  1.9373,  0.7287]]]),
 torch.Size([2, 3, 3]))

In [300]:
torch.narrow(ar, 2, 0 , 4), torch.narrow(ar, 2, 0 , 4).shape

(tensor([[[-8.7189e-01, -2.7118e-02, -3.5325e-01,  1.4639e+00],
          [ 1.7290e-01,  1.0514e+00,  7.4915e-03, -7.7365e-02],
          [ 8.3509e-01, -3.1571e-01,  2.6911e-01,  8.5404e-02]],
 
         [[-1.3793e+00,  6.2580e-01, -2.5850e+00, -2.4000e-02],
          [ 5.2394e-01, -2.6935e-01, -1.6191e+00,  1.2588e-03],
          [ 1.1930e+00,  1.9373e+00,  7.2871e-01,  9.8089e-01]]]),
 torch.Size([2, 3, 4]))

In [302]:
ar.shape, ar

(torch.Size([2, 3, 4]),
 tensor([[[-8.7189e-01, -2.7118e-02, -3.5325e-01,  1.4639e+00],
          [ 1.7290e-01,  1.0514e+00,  7.4915e-03, -7.7365e-02],
          [ 8.3509e-01, -3.1571e-01,  2.6911e-01,  8.5404e-02]],
 
         [[-1.3793e+00,  6.2580e-01, -2.5850e+00, -2.4000e-02],
          [ 5.2394e-01, -2.6935e-01, -1.6191e+00,  1.2588e-03],
          [ 1.1930e+00,  1.9373e+00,  7.2871e-01,  9.8089e-01]]]))

In [303]:
## it we want to save it some where and dont want to share the memory then we use narrow_copy()

In [309]:
ar.shape

torch.Size([2, 3, 4])

In [310]:
e1  = torch.narrow_copy(ar, -1, 0, ar.shape[-1])
e1

tensor([[[-8.7189e-01, -2.7118e-02, -3.5325e-01,  1.4639e+00],
         [ 1.7290e-01,  1.0514e+00,  7.4915e-03, -7.7365e-02],
         [ 8.3509e-01, -3.1571e-01,  2.6911e-01,  8.5404e-02]],

        [[-1.3793e+00,  6.2580e-01, -2.5850e+00, -2.4000e-02],
         [ 5.2394e-01, -2.6935e-01, -1.6191e+00,  1.2588e-03],
         [ 1.1930e+00,  1.9373e+00,  7.2871e-01,  9.8089e-01]]])

Feature	torch.narrow() (View)	torch.narrow_copy() (Copy)

Memory Sharing	Shares memory with original tensor	Creates a new memory allocation

In-Place Safety	Risky (modifications affect original)	Safe (independent of original)

Performance	Faster (no data duplication)	Slower (data copied)

Use Case	Efficient data subset extraction	Isolated operations on the subset

In [311]:
## non zeros

In [312]:
t = torch.randn(2,3,4)
t, t.shape

(tensor([[[ 0.7987,  0.9105, -0.0880,  0.3370],
          [ 0.9733, -1.0151, -0.5419, -0.4410],
          [ 0.4536,  1.2461, -2.3065, -1.2869]],
 
         [[ 0.2137, -1.2351,  1.8592,  0.0561],
          [-0.7647, -0.0553,  1.2049, -0.9825],
          [ 0.3040,  0.9339, -1.9726, -1.4120]]]),
 torch.Size([2, 3, 4]))

In [314]:
# this will return the index 

torch.nonzero(t)

tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 2],
        [0, 0, 3],
        [0, 1, 0],
        [0, 1, 1],
        [0, 1, 2],
        [0, 1, 3],
        [0, 2, 0],
        [0, 2, 1],
        [0, 2, 2],
        [0, 2, 3],
        [1, 0, 0],
        [1, 0, 1],
        [1, 0, 2],
        [1, 0, 3],
        [1, 1, 0],
        [1, 1, 1],
        [1, 1, 2],
        [1, 1, 3],
        [1, 2, 0],
        [1, 2, 1],
        [1, 2, 2],
        [1, 2, 3]])

### permute | transpose | swapaxes | swapdims.


In [317]:
x = torch.randn(2,3,4)
x

tensor([[[ 0.9624, -0.1426,  0.1527, -0.0388],
         [-0.2130, -0.5904,  0.4668,  0.3956],
         [-0.3016, -1.4033, -1.3271, -0.9948]],

        [[-0.4940,  1.1366, -0.4618,  1.4200],
         [ 0.8211, -0.0675,  0.9491, -0.3983],
         [ 0.6899, -1.3129,  0.0378, -1.1702]]])

In [319]:
x.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [326]:
x.shape

torch.Size([2, 3, 4])

In [323]:
torch.swapaxes(x, 2,0).shape

torch.Size([4, 3, 2])

In [328]:
torch.swapdims(x, 2, 0).shape

torch.Size([4, 3, 2])

In [329]:
x.shape

torch.Size([2, 3, 4])

In [331]:
x.transpose(0,1).shape

torch.Size([3, 2, 4])

In [332]:
x , x.transpose(0,1)

(tensor([[[ 0.9624, -0.1426,  0.1527, -0.0388],
          [-0.2130, -0.5904,  0.4668,  0.3956],
          [-0.3016, -1.4033, -1.3271, -0.9948]],
 
         [[-0.4940,  1.1366, -0.4618,  1.4200],
          [ 0.8211, -0.0675,  0.9491, -0.3983],
          [ 0.6899, -1.3129,  0.0378, -1.1702]]]),
 tensor([[[ 0.9624, -0.1426,  0.1527, -0.0388],
          [-0.4940,  1.1366, -0.4618,  1.4200]],
 
         [[-0.2130, -0.5904,  0.4668,  0.3956],
          [ 0.8211, -0.0675,  0.9491, -0.3983]],
 
         [[-0.3016, -1.4033, -1.3271, -0.9948],
          [ 0.6899, -1.3129,  0.0378, -1.1702]]]))

In [333]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [334]:
x.reshape(2,2)

tensor([[0, 1],
        [2, 3]])

In [335]:
x

tensor([0, 1, 2, 3])

In [336]:
x.unsqueeze(0)

tensor([[0, 1, 2, 3]])

In [339]:
y = torch.tensor([[[[[1]]]]])

In [340]:
y

tensor([[[[[1]]]]])

In [341]:
y.shape

torch.Size([1, 1, 1, 1, 1])

In [345]:
z = y.squeeze()
z

tensor(1)

In [349]:
z.unsqueeze(0)

tensor([1])

In [350]:
z = z.unsqueeze(0)
z, z.shape

(tensor([1]), torch.Size([1]))

In [352]:
z.unsqueeze(0), z.unsqueeze(0).shape

(tensor([[1]]), torch.Size([1, 1]))

In [368]:
t = torch.zeros(3,5, dtype=torch.float64)
index = torch.tensor([[0,1,2],[2,0,4],[3,1,3]])
src = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float64)

In [369]:
torch.scatter(t, 1, index, src)

tensor([[1., 2., 3., 0., 0.],
        [5., 0., 4., 0., 6.],
        [0., 8., 0., 9., 0.]], dtype=torch.float64)

In [370]:
# an in-place method:
# input.scatter_(dim, index, src, reduce=None)

In [371]:
t.shape

torch.Size([3, 5])

In [376]:
# inplace methods
t.scatter_(0, torch.tensor([[0,2]]), torch.tensor([[1, 5]], dtype=torch.float64))
t

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0.]], dtype=torch.float64)

In [377]:
t

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0.]], dtype=torch.float64)

In [378]:
# 3. scatter_add_
# Adds values from src to input at specified indices instead of overwriting.

# Useful when multiple values map to the same index and you want to accumulate.


In [387]:
z = torch.randn(3,4,  dtype=torch.float64)
z, z.shape

(tensor([[ 1.4372, -0.7067,  1.3422,  0.5235],
         [-0.2640, -0.3286, -0.3712, -0.5473],
         [ 1.3824, -0.7472, -2.5696,  0.1018]], dtype=torch.float64),
 torch.Size([3, 4]))

In [388]:
index = torch.tensor([[0,2],[2,2]])
src = torch.tensor([[3,5],[4,4]], dtype=torch.float64)

src

tensor([[3., 5.],
        [4., 4.]], dtype=torch.float64)

In [389]:
index

tensor([[0, 2],
        [2, 2]])

In [392]:
z.scatter_add(0, index, src), z.scatter_add(1, index, src)

(tensor([[ 4.4372, -0.7067,  1.3422,  0.5235],
         [-0.2640, -0.3286, -0.3712, -0.5473],
         [ 5.3824,  8.2528, -2.5696,  0.1018]], dtype=torch.float64),
 tensor([[ 4.4372, -0.7067,  6.3422,  0.5235],
         [-0.2640, -0.3286,  7.6288, -0.5473],
         [ 1.3824, -0.7472, -2.5696,  0.1018]], dtype=torch.float64))

In [393]:
# scatter with reduce argument (PyTorch 1.10+)
# Supports reduction operations like 'add', 'multiply', 'mean', 'min', 'max' when multiple writes target the same index.



In [394]:
t = torch.arange(10)

torch.split(t, 3)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([9]))

In [395]:
torch.tensor_split(t, [3,6,8])

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7]), tensor([8, 9]))

In [396]:
torch.tensor_split(t, [4,6,8])

(tensor([0, 1, 2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9]))

In [397]:
## stack / unbind 

a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

a,b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [399]:
torch.stack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [400]:
torch.hstack((a,b))

tensor([1, 2, 3, 4, 5, 6])

In [402]:
c = torch.vstack((a,b))
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [403]:
z = torch.unbind(c)

In [404]:
z

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [405]:
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [408]:
torch.unbind(c, dim=1)

(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))

In [409]:
c.shape

torch.Size([2, 3])

In [410]:
## take / take_along_dim 

t = torch.tensor([[10,20], [30,40]])
t

tensor([[10, 20],
        [30, 40]])

In [415]:
t.shape

torch.Size([2, 2])

In [411]:
torch.take(t, torch.tensor([0,2]))

tensor([10, 30])

In [412]:
torch.take(t, torch.tensor([0,3]))

tensor([10, 40])

In [413]:
## 
indices = torch.tensor([[0,0],[1,0]])
indices

tensor([[0, 0],
        [1, 0]])

In [414]:
torch.take_along_dim(t, indices, dim=1)

tensor([[10, 10],
        [40, 30]])

In [416]:
# tiles 

In [418]:
a = torch.tensor([0,1,2])

print(torch.tile(a, (2,3)))

tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2]])


In [419]:
a, a.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [421]:
# dims (tuple): the number of repetitions per dimension.


# tile(input, dims) -> Tensor

# Constructs a tensor by repeating the elements of input.
# The dims argument specifies the number of repetitions in each dimension.

In [422]:
a = torch.tensor([0,1,2,3])

print(torch.tile(a, (1,2)))

tensor([[0, 1, 2, 3, 0, 1, 2, 3]])


In [424]:
## unravel index 

indices = torch.tensor([22, 41, 37])
shape = (7,6)

torch.unravel_index(indices, shape)

(tensor([3, 6, 6]), tensor([4, 5, 1]))

In [425]:
# How the Mapping Works
# For a 2D tensor with shape (rows, columns), the mapping is:

# row = index // columns

# column = index % columns

# Apply to Each Index
# 22:

# row = 22 // 6 = 3

# col = 22 % 6 = 4

# → (3, 4)

# 41:

# row = 41 // 6 = 6

# col = 41 % 6 = 5

# → (6, 5)

# 37:

# row = 37 // 6 = 6

# col = 37 % 6 = 1

# → (6, 1)

In [426]:
## where 

x = torch.tensor([1,2,3,4])
y = torch.tensor([9,8,7,6])

x, y

(tensor([1, 2, 3, 4]), tensor([9, 8, 7, 6]))

In [427]:
cond = torch.tensor([True, False, True, False])

torch.where(cond, x, y)

tensor([1, 8, 3, 6])

In [428]:
# Output element (from x if cond True else y)

In [429]:
# torch.where(condition, x, y) returns a tensor where each element is selected from x if the corresponding element in condition is True, otherwise from y.

# It works element-wise, meaning it checks each element of condition and picks from x or y accordingly.

