In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
else:
    print("cuda is not available")

cuda is available


In [ ]:
torch.cuda.device_count()

1

## Tensors

In [ ]:
a =  torch.empty(2,3)
a

tensor([[5.5894e-08, 4.5371e-41, 5.5893e-08],
        [4.5371e-41, 3.2254e-03, 4.5371e-41]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
b = torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
b = torch.zeros((3,))

In [ ]:
b

tensor([0., 0., 0.])

In [ ]:
one = torch.ones((1,2))

In [ ]:
one

tensor([[1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.7404, 0.7481, 0.9813],
        [0.2901, 0.5270, 0.8640]])

In [ ]:
torch.seed = 42

In [ ]:
torch.seed = 42
torch.rand(2,3)

tensor([[0.1454, 0.9810, 0.3291],
        [0.5304, 0.5698, 0.3271]])

In [ ]:
torch.seed = 42
torch.rand(2,3)

tensor([[0.7138, 0.7430, 0.2963],
        [0.9720, 0.6625, 0.3312]])

### how to define the seed in torch

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

## array or list to tensor

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
import numpy as np

In [ ]:
c = torch.tensor(np.array([[2,3],[4,5]]))
c

tensor([[2, 3],
        [4, 5]])

In [ ]:
type(c)

torch.Tensor

In [ ]:
c.shape

torch.Size([2, 2])

In [ ]:
c.size()

torch.Size([2, 2])

In [ ]:
c

tensor([[2, 3],
        [4, 5]])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [ ]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.logspace(0,10,10)

tensor([1.0000e+00, 1.2915e+01, 1.6681e+02, 2.1544e+03, 2.7826e+04, 3.5938e+05,
        4.6416e+06, 5.9948e+07, 7.7426e+08, 1.0000e+10])

In [ ]:
torch.linspace(0,10,10).reshape(5,2)

tensor([[ 0.0000,  1.1111],
        [ 2.2222,  3.3333],
        [ 4.4444,  5.5556],
        [ 6.6667,  7.7778],
        [ 8.8889, 10.0000]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [ ]:
d = torch.arange(0,20,2).reshape(2,5)
d

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [ ]:
d.shape

torch.Size([2, 5])

In [ ]:
torch.empty_like(d)

tensor([[     139067059279600,                  161,      139067065548000,
              100051804614976,      139067022321776],
        [     139062883658208, -4187494740023593838,      139067059459248,
              139062883647936,  4532340397604536772]])

In [ ]:
torch.zeros_like(d)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [ ]:
torch.ones_like(d)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [ ]:
torch.rand_like(d)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

## Data Type

In [ ]:
d.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0])

tensor([1., 2., 3.])

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
m = torch.tensor([1,2,3],dtype=torch.float)
m

tensor([1., 2., 3.])

In [ ]:
m.dtype

torch.float32

In [ ]:
d

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

#### Use .to method

In [ ]:
d.to(torch.float64)

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]], dtype=torch.float64)

In [ ]:
torch.rand_like(d,dtype=torch.float64)

tensor([[0.0526, 0.5262, 0.4768, 0.9552, 0.9288],
        [0.0835, 0.1326, 0.1571, 0.3754, 0.8425]], dtype=torch.float64)

## Mathematical Operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.3588, 0.1994],
        [0.5472, 0.0062]])

In [ ]:
x+2

tensor([[2.3588, 2.1994],
        [2.5472, 2.0062]])

In [ ]:
x-2

tensor([[-1.6412, -1.8006],
        [-1.4528, -1.9938]])

In [ ]:
x*2

tensor([[0.7176, 0.3987],
        [1.0944, 0.0123]])

In [ ]:
x**2

tensor([[1.2875e-01, 3.9746e-02],
        [2.9942e-01, 3.7951e-05]])

In [ ]:
x/2

tensor([[0.1794, 0.0997],
        [0.2736, 0.0031]])

In [ ]:
x*100//2

tensor([[17.,  9.],
        [27.,  0.]])

In [ ]:
x*100%10

tensor([[5.8813, 9.9364],
        [4.7192, 0.6160]])

In [ ]:
x**10

tensor([[3.5373e-05, 9.9189e-08],
        [2.4065e-03, 7.8726e-23]])

In [ ]:
a = torch.randint(0,10,(2,2))
b = torch.randint(0,10,(2,2))

In [ ]:
a

tensor([[2, 0],
        [5, 9]])

In [ ]:
b

tensor([[3, 4],
        [9, 6]])

In [ ]:
a + b

tensor([[ 5,  4],
        [14, 15]])

In [ ]:
a - b

tensor([[-1, -4],
        [-4,  3]])

In [ ]:
a * b

tensor([[ 6,  0],
        [45, 54]])

In [ ]:
a @ b

tensor([[ 6,  8],
        [96, 74]])

In [ ]:
a / b

tensor([[0.6667, 0.0000],
        [0.5556, 1.5000]])

In [ ]:
a // b

tensor([[0, 0],
        [0, 1]])

In [ ]:
a % b

tensor([[2, 0],
        [5, 3]])

In [ ]:
x = torch.tensor([1,-2,3,4])
x

tensor([ 1, -2,  3,  4])

In [ ]:
torch.abs(x)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(x)

tensor([-1,  2, -3, -4])

In [ ]:
t = torch.tensor([2.2,3.1,3.5,4.6,5.5])
t

tensor([2.2000, 3.1000, 3.5000, 4.6000, 5.5000])

In [ ]:
torch.round(t)

tensor([2., 3., 4., 5., 6.])

In [ ]:
torch.ceil(t)

tensor([3., 4., 4., 5., 6.])

In [ ]:
torch.floor(t)

tensor([2., 3., 3., 4., 5.])

In [ ]:
torch.clamp(t,min=3,max=4)

tensor([3.0000, 3.1000, 3.5000, 4.0000, 4.0000])

In [ ]:
q = torch.randint(size=(2,3), low = 0, high = 10)
q

tensor([[2, 0, 6],
        [2, 7, 9]])

In [ ]:
torch.sum(q)

tensor(26)

In [ ]:
torch.sum(q,dim=0)

tensor([ 4,  7, 15])

In [ ]:
torch.sum(q,dim=1)

tensor([ 8, 18])

In [ ]:
torch.sum(q)

tensor(26)

In [ ]:
q

tensor([[2, 0, 6],
        [2, 7, 9]])

In [ ]:
q.dtype

torch.int64

In [ ]:
torch.mean(q,dtype=torch.float32)

tensor(4.3333)

In [ ]:
torch.mean(q, dim=0, dtype=torch.float32)

tensor([2.0000, 3.5000, 7.5000])

In [ ]:
torch.mean(q, dim=1, dtype=torch.float32)

tensor([2.6667, 6.0000])

In [ ]:
torch.median(q)

tensor(2)

In [ ]:
torch.median(q, dim=1)

torch.return_types.median(
values=tensor([2, 7]),
indices=tensor([0, 1]))

In [ ]:
torch.min(q)

tensor(0)

In [ ]:
torch.max(q)

tensor(9)

In [ ]:
torch.prod(q)

tensor(0)

In [ ]:
e = torch.randint(1,10,size=(4,3))
e

tensor([[4, 9, 6],
        [5, 1, 3],
        [4, 1, 2],
        [1, 8, 5]])

In [ ]:
torch.prod(e)

tensor(1036800)

In [ ]:
torch.max(e)

tensor(9)

In [ ]:
torch.min(e)

tensor(1)

In [ ]:
torch.std(e,dtype=torch.float32)

TypeError: std() received an invalid combination of arguments - got (Tensor, dtype=torch.dtype), but expected one of:
 * (Tensor input, tuple of ints dim, bool unbiased = True, bool keepdim = False, *, Tensor out = None)
 * (Tensor input, tuple of ints dim = None, *, Number correction = None, bool keepdim = False, Tensor out = None)
 * (Tensor input, bool unbiased = True)
      didn't match because some of the keywords were incorrect: dtype
 * (Tensor input, tuple of names dim, bool unbiased = True, bool keepdim = False, *, Tensor out = None)
 * (Tensor input, tuple of names dim, *, Number correction = None, bool keepdim = False, Tensor out = None)


In [ ]:
e

tensor([[4, 9, 6],
        [5, 1, 3],
        [4, 1, 2],
        [1, 8, 5]])

In [ ]:
e = e.to(torch.float32)

In [ ]:
e

tensor([[4., 9., 6.],
        [5., 1., 3.],
        [4., 1., 2.],
        [1., 8., 5.]])

In [ ]:
e.dtype

torch.float32

In [ ]:
torch.std(e)

tensor(2.6785)

In [ ]:
torch.var(e)

tensor(7.1742)

In [ ]:
## Argmax
torch.argmax(e)

tensor(1)

In [ ]:
e

tensor([[4., 9., 6.],
        [5., 1., 3.],
        [4., 1., 2.],
        [1., 8., 5.]])

In [ ]:
torch.argmax(e, dim=0)

tensor([1, 0, 0])

In [ ]:
torch.argmax(e, dim=1)

tensor([1, 0, 0, 1])

In [ ]:
## Matrix multiplication

In [ ]:
import torch

In [ ]:
a1 = torch.randint(0,10,(2,3))
a2 = torch.randint(0,10,(3,2))

In [ ]:
torch.matmul(a1,a2)

tensor([[61, 39],
        [48, 36]])

In [ ]:
vector1 = torch.tensor([1,2,3,4])
vector2 = torch.tensor([2,3,5,6])

In [ ]:
torch.dot(vector1, vector2)

tensor(47)

In [ ]:
a1 = a1.to(torch.float32)

In [ ]:
torch.linalg.matrix_rank(a1)

tensor(2)

In [ ]:
torch.transpose(a1)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [ ]:
a1

tensor([[5., 2., 8.],
        [4., 8., 6.]])

In [ ]:
torch.transpose(a1, 0, 1)

tensor([[5., 4.],
        [2., 8.],
        [8., 6.]])

In [ ]:
a1

tensor([[5., 2., 8.],
        [4., 8., 6.]])

In [ ]:
a1 = torch.randint(0,10,(3,3), dtype=torch.float32)

In [ ]:
torch.linalg.det(a1)

tensor(26.)

In [ ]:
torch.linalg.inv(a1)

tensor([[-1.4615,  0.5769, -0.0769],
        [ 1.8462, -0.8077,  0.3077],
        [ 0.0769,  0.1538, -0.1538]])

In [ ]:
a1 = torch.randint(0,10,(3,3), dtype=torch.float32)
a2 = torch.randint(0,10,(3,3), dtype=torch.float32)
a1, a2

(tensor([[6., 1., 5.],
         [6., 6., 2.],
         [9., 9., 0.]]),
 tensor([[4., 7., 5.],
         [2., 7., 4.],
         [5., 5., 8.]]))

In [ ]:
a1 > a2

tensor([[ True, False, False],
        [ True, False, False],
        [ True,  True, False]])

In [ ]:
a1 < a2

tensor([[False,  True, False],
        [False,  True,  True],
        [False, False,  True]])

In [ ]:
a1[a1 > a2]

tensor([6., 6., 9., 9.])

In [ ]:
a1[a1 == a2]

tensor([5.])

In [ ]:
a1

tensor([[6., 1., 5.],
        [6., 6., 2.],
        [9., 9., 0.]])

In [ ]:
a2

tensor([[4., 7., 5.],
        [2., 7., 4.],
        [5., 5., 8.]])

In [ ]:
a1 == a2

tensor([[False, False,  True],
        [False, False, False],
        [False, False, False]])

In [ ]:
a1 != a2

tensor([[ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True]])

In [ ]:
a1

tensor([[6., 1., 5.],
        [6., 6., 2.],
        [9., 9., 0.]])

In [ ]:
torch.log(a1)

tensor([[1.7918, 0.0000, 1.6094],
        [1.7918, 1.7918, 0.6931],
        [2.1972, 2.1972,   -inf]])

In [ ]:
torch.exp(a1)

tensor([[4.0343e+02, 2.7183e+00, 1.4841e+02],
        [4.0343e+02, 4.0343e+02, 7.3891e+00],
        [8.1031e+03, 8.1031e+03, 1.0000e+00]])

In [ ]:
torch.sqrt(a1)

tensor([[2.4495, 1.0000, 2.2361],
        [2.4495, 2.4495, 1.4142],
        [3.0000, 3.0000, 0.0000]])

In [ ]:
## Sigmoid

In [ ]:
torch.sigmoid(a1)

tensor([[0.9975, 0.7311, 0.9933],
        [0.9975, 0.9975, 0.8808],
        [0.9999, 0.9999, 0.5000]])

In [ ]:
torch.softmax(a1)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [ ]:
torch.softmax(a1, dim=0)

tensor([[4.5279e-02, 3.1945e-04, 9.4650e-01],
        [4.5279e-02, 4.7411e-02, 4.7123e-02],
        [9.0944e-01, 9.5227e-01, 6.3775e-03]])

In [ ]:
a1

tensor([[6., 1., 5.],
        [6., 6., 2.],
        [9., 9., 0.]])

In [ ]:
torch.relu(a1)

tensor([[6., 1., 5.],
        [6., 6., 2.],
        [9., 9., 0.]])

In [ ]:
### Inplace Operation

In [ ]:
n1 = torch.randint(1,10,(3,3), dtype=torch.float32)
n2 = torch.randint(1,10,(3,3), dtype=torch.float32)
n1,n2

(tensor([[2., 5., 4.],
         [6., 5., 3.],
         [7., 3., 6.]]),
 tensor([[9., 4., 8.],
         [4., 5., 7.],
         [2., 5., 5.]]))

In [ ]:
n1.add_(n2)

tensor([[11.,  9., 12.],
        [10., 10., 10.],
        [ 9.,  8., 11.]])

In [ ]:
## value changed of n1
n1

tensor([[11.,  9., 12.],
        [10., 10., 10.],
        [ 9.,  8., 11.]])

In [ ]:
n2

tensor([[9., 4., 8.],
        [4., 5., 7.],
        [2., 5., 5.]])

In [ ]:
n2

tensor([[9., 4., 8.],
        [4., 5., 7.],
        [2., 5., 5.]])

In [ ]:
torch.relu(n2,)

tensor([[9., 4., 8.],
        [4., 5., 7.],
        [2., 5., 5.]])

In [ ]:
n2

tensor([[9., 4., 8.],
        [4., 5., 7.],
        [2., 5., 5.]])

In [ ]:
n2.relu_()

tensor([[9., 4., 8.],
        [4., 5., 7.],
        [2., 5., 5.]])

In [ ]:
n2

tensor([[9., 4., 8.],
        [4., 5., 7.],
        [2., 5., 5.]])

In [ ]:
torch.sigmoid(n2)

tensor([[0.9999, 0.9820, 0.9997],
        [0.9820, 0.9933, 0.9991],
        [0.8808, 0.9933, 0.9933]])

In [ ]:
n2

tensor([[9., 4., 8.],
        [4., 5., 7.],
        [2., 5., 5.]])

In [ ]:
n2.sigmoid_()

tensor([[0.9999, 0.9820, 0.9997],
        [0.9820, 0.9933, 0.9991],
        [0.8808, 0.9933, 0.9933]])

In [ ]:
n2

tensor([[0.9999, 0.9820, 0.9997],
        [0.9820, 0.9933, 0.9991],
        [0.8808, 0.9933, 0.9933]])

In [ ]:
### so what we learn is
### just put the underscore.

In [ ]:
## Copying tensor

In [ ]:
a = torch.randint(1,10,(2,2))
a

tensor([[8, 8],
        [8, 1]])

In [ ]:
b = a

In [ ]:
b

tensor([[8, 8],
        [8, 1]])

In [ ]:
b[0,0] = 0

In [ ]:
b

tensor([[0, 8],
        [8, 1]])

In [ ]:
a

tensor([[0, 8],
        [8, 1]])

In [ ]:
id(b), id(a)

(132151306320240, 132151306320240)

In [ ]:
### it is a soft copy

In [ ]:
a

tensor([[0, 8],
        [8, 1]])

In [ ]:
b

tensor([[0, 8],
        [8, 1]])

In [ ]:
b = a.clone()
b

tensor([[0, 8],
        [8, 1]])

In [ ]:
b[0][0] = 10

In [ ]:
b

tensor([[10,  8],
        [ 8,  1]])

In [ ]:
a

tensor([[0, 8],
        [8, 1]])

In [ ]:
id(a), id(b)

(132151306320240, 132151291797216)

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda")

In [ ]:
device

device(type='cuda')

In [ ]:
n1 = torch.rand((2,2), device=device)

In [ ]:
n1

tensor([[0.7398, 0.1643],
        [0.8077, 0.2275]], device='cuda:0')

In [ ]:
## Cpu
n2 = torch.rand((2,2))
n2

tensor([[0.8431, 0.8556],
        [0.8563, 0.5957]])

In [ ]:
b = n2.to(device)
b

tensor([[0.8431, 0.8556],
        [0.8563, 0.5957]], device='cuda:0')

In [ ]:
b + 5

tensor([[5.8431, 5.8556],
        [5.8563, 5.5957]], device='cuda:0')

In [ ]:
n2 + 5

tensor([[5.8431, 5.8556],
        [5.8563, 5.5957]])

In [ ]:
import torch
import time

In [ ]:
## performing time
size = 1000

m1 = torch.randn(size,size)
m2 = torch.randn(size,size)

start_time = time.time()
r_c = torch.matmul(m1,m2)
cpu_time = time.time() - start_time

print(f"time taken by the cpu {cpu_time}")

time taken by the cpu 0.026363134384155273


In [ ]:
## performing time
size = 1000

m1 = torch.randn(size,size)
m2 = torch.randn(size,size)

m1 = m1.to("cuda")
m2 = m2.to("cuda")

start_time = time.time()
r_c = torch.matmul(m1,m2)
cuda_time = time.time() - start_time

print(f"time taken to performe operation on TPU {cuda_time}")

time taken to performe operation on TPU 0.0001735687255859375


In [ ]:
print(f"speed up by {cpu_time/cuda_time}")

speed up by 151.88873626373626


In [ ]:
## Reshaping

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
b = torch.ones((2,4,3))
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
b.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])

In [ ]:
## permute

In [ ]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
b.shape

torch.Size([2, 4, 3])

In [ ]:
b.permute(2,0,1)
##        3 2 4

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([3, 2, 4])

In [ ]:
## unsqueeze

In [ ]:
c = torch.rand(226,226,3)
c

tensor([[[3.0502e-02, 7.5836e-01, 7.8484e-01],
         [1.9896e-01, 3.0000e-01, 4.8201e-01],
         [5.9415e-03, 7.5565e-01, 7.1070e-01],
         ...,
         [7.6855e-01, 2.8204e-01, 5.7382e-01],
         [8.0229e-01, 1.3559e-01, 7.3805e-01],
         [1.0130e-01, 7.8142e-01, 8.0308e-01]],

        [[9.2798e-01, 5.8330e-01, 9.0366e-01],
         [6.7091e-01, 6.2801e-01, 9.3279e-01],
         [6.9471e-01, 7.4930e-01, 8.3153e-01],
         ...,
         [4.8569e-01, 8.4190e-01, 7.6711e-01],
         [8.2551e-01, 1.3561e-01, 9.9647e-01],
         [9.9549e-01, 8.0663e-01, 9.5888e-03]],

        [[6.9643e-01, 2.1515e-01, 2.1401e-01],
         [7.1816e-01, 3.4719e-01, 3.7216e-01],
         [5.5931e-01, 5.8258e-01, 3.9500e-01],
         ...,
         [7.4280e-01, 7.5274e-01, 1.7836e-01],
         [6.0206e-02, 5.9582e-01, 8.6428e-01],
         [4.5747e-04, 9.8360e-01, 4.6798e-01]],

        ...,

        [[6.2961e-01, 1.1144e-01, 7.1480e-01],
         [1.2374e-01, 5.8787e-01, 8.4028e-01]

In [ ]:
c.shape

torch.Size([226, 226, 3])

In [ ]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
c.unsqueeze(-1).shape

torch.Size([226, 226, 3, 1])

In [ ]:
c.unsqueeze(3).shape

torch.Size([226, 226, 3, 1])

In [ ]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
## it is adding new dimension

In [ ]:
## squeeze

In [ ]:
d = torch.rand(1,20, dtype=torch.float32)
d

tensor([[0.2483, 0.6007, 0.7693, 0.7458, 0.3953, 0.1095, 0.2322, 0.3341, 0.4022,
         0.9940, 0.9467, 0.9980, 0.9641, 0.2926, 0.0710, 0.9342, 0.7662, 0.2036,
         0.1919, 0.5840]])

In [ ]:
d.squeeze()

tensor([0.2483, 0.6007, 0.7693, 0.7458, 0.3953, 0.1095, 0.2322, 0.3341, 0.4022,
        0.9940, 0.9467, 0.9980, 0.9641, 0.2926, 0.0710, 0.9342, 0.7662, 0.2036,
        0.1919, 0.5840])

In [ ]:
d.squeeze().shape

torch.Size([20])

In [ ]:
## numpy and tensor

In [ ]:
import numpy as np

In [ ]:
import torch

In [ ]:
t1 = torch.tensor([1,2,4])
t1

tensor([1, 2, 4])

In [ ]:
a = t1.numpy()

In [ ]:
a.dtype

dtype('int64')

In [ ]:
t1.dtype

torch.int64

In [ ]:
## from numpy to tensor

In [ ]:
t2 = torch.from_numpy(a)
t2

tensor([1, 2, 4])

In [ ]:
t2.dtype

torch.int64