In [1]:
print("Hello  I Am Dhruv Panchal")

Hello  I Am Dhruv Panchal


In [2]:
## nvidia-smi

In [3]:
import torch

In [4]:
print(torch.__version__)

2.5.1+cpu


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
## scaler tensor 

a = torch.tensor([1])
a

tensor([1])

In [7]:
a.shape

torch.Size([1])

In [8]:
a.size()

torch.Size([1])

In [10]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [11]:
scaler.shape

torch.Size([])

In [12]:
a[-1]

tensor(1)

In [13]:
scaler.ndim

0

In [14]:
a.ndim

1

In [16]:
a.item()

1

In [17]:
scaler.item()

7

In [18]:
# vector tensor

b = torch.tensor([1,2,3,4])
b.shape

torch.Size([4])

In [19]:
b.size(), b.ndim

(torch.Size([4]), 1)

In [20]:
b.item()

RuntimeError: a Tensor with 4 elements cannot be converted to Scalar

In [1]:
import torch

In [4]:
b = torch.tensor([1,2,3])
b.shape, b.size(), b.ndim

(torch.Size([3]), torch.Size([3]), 1)

In [5]:
b.item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [9]:
b.float()

tensor([1., 2., 3.])

In [10]:
b.device

device(type='cpu')

In [11]:
b.abs()

tensor([1, 2, 3])

In [12]:
b.absolute()

tensor([1, 2, 3])

In [14]:
b.name

In [20]:
b.ceil()

tensor([1, 2, 3])

In [21]:
b.floor()

tensor([1, 2, 3])

## Random tensor

In [22]:
## why random rensor ?

## random rensors are important bcause the way many neural networks learn is that they start with tensors full of the random numbers and then adjust those random numbers to better represent the data


In [23]:
## start witj random number --> look at data -- > update random numner --> look at the data -- > update the random number

In [24]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8956, 0.2574, 0.2992, 0.6917],
        [0.8820, 0.2544, 0.3582, 0.0323],
        [0.4948, 0.0417, 0.2870, 0.3665]])

In [25]:
random_tensor.shape

torch.Size([3, 4])

In [26]:
random_tensor.dtype

torch.float32

In [27]:
random_tensor.ndim

2

In [28]:
random_ = torch.rand(1,10,10)
random_

tensor([[[0.5828, 0.8067, 0.4023, 0.3436, 0.5591, 0.0123, 0.9637, 0.1230,
          0.4255, 0.1445],
         [0.8546, 0.6575, 0.7110, 0.2865, 0.9043, 0.5587, 0.9088, 0.3406,
          0.3521, 0.3055],
         [0.7513, 0.6684, 0.8654, 0.7433, 0.6770, 0.3617, 0.9849, 0.0768,
          0.3132, 0.1692],
         [0.9001, 0.6834, 0.0754, 0.5768, 0.6403, 0.6783, 0.2522, 0.4669,
          0.9112, 0.2950],
         [0.7570, 0.1311, 0.3366, 0.0567, 0.7868, 0.9277, 0.1584, 0.5035,
          0.4483, 0.4397],
         [0.1602, 0.7503, 0.5899, 0.3963, 0.0851, 0.3251, 0.7340, 0.3623,
          0.3852, 0.6508],
         [0.5125, 0.4219, 0.2468, 0.5657, 0.7759, 0.6912, 0.4017, 0.1335,
          0.7108, 0.8452],
         [0.4200, 0.9308, 0.9557, 0.5901, 0.3867, 0.3622, 0.4765, 0.1538,
          0.5950, 0.0980],
         [0.3232, 0.9569, 0.4685, 0.6973, 0.0711, 0.3032, 0.4882, 0.9864,
          0.5469, 0.1835],
         [0.5764, 0.6063, 0.5657, 0.7536, 0.2540, 0.4941, 0.1003, 0.5615,
          0.1022,

In [29]:
random_.shape

torch.Size([1, 10, 10])

In [30]:
random_.ndim

3

In [31]:
random_.device

device(type='cpu')

In [32]:
random_ = torch.rand(10,10,10)
random_

tensor([[[1.8267e-02, 5.7058e-01, 5.8448e-01, 7.5917e-01, 5.8727e-01,
          9.8462e-01, 2.6117e-01, 3.7830e-03, 7.1268e-01, 4.8514e-01],
         [1.9704e-01, 7.4120e-01, 2.8855e-01, 5.1055e-01, 1.5031e-01,
          5.1669e-02, 9.6893e-01, 5.6997e-01, 6.8020e-01, 2.9622e-01],
         [9.1296e-01, 1.9695e-01, 7.7431e-01, 7.6489e-01, 7.7456e-01,
          6.4722e-01, 9.2022e-01, 1.6818e-01, 7.8254e-01, 5.3020e-01],
         [6.3441e-01, 1.2416e-01, 2.6444e-01, 5.3291e-01, 6.9353e-01,
          9.0978e-01, 5.4169e-01, 7.7453e-01, 3.1834e-01, 4.3218e-01],
         [7.5887e-01, 9.2264e-01, 5.4658e-01, 5.3200e-01, 6.1806e-01,
          2.4499e-01, 5.7078e-01, 5.4605e-01, 8.4094e-01, 3.0703e-01],
         [8.5160e-01, 1.6452e-01, 2.2471e-01, 8.2102e-01, 5.4763e-01,
          4.8485e-01, 1.8907e-01, 1.9733e-01, 6.7166e-01, 4.8316e-01],
         [9.2779e-01, 8.5920e-01, 1.3998e-02, 7.3811e-01, 3.3144e-01,
          3.7348e-01, 1.4420e-01, 7.8359e-01, 7.1880e-01, 3.4304e-01],
         [1.5

In [33]:
random_.ndim

3

In [41]:
random_.shape

torch.Size([10, 10, 10])

In [ ]:
## lets create a random tensor of same size as image 

random_size_iamge_size = torch.random()